mattermost/mattermost-load-test-ng

- cmd/loadtest/main.go
- config/config.go
Adds a global `--config|-c` flag and loads the configuration from a file if it is set.
https://mattermost.atlassian.net/browse/MM-20298
> [MM-20298] Add --config|-c flag to read the config from a file

- example/loadtest.go
- example/samplecontroller/controller.go
- loadtest/control/controller.go
- loadtest/control/simplecontroller/actions.go
- loadtest/control/simplecontroller/controller.go
- loadtest/control/simplecontroller/status.go
- loadtest/control/status.go
- loadtest/run.go
- loadtest/user/user.go
PR moves `UserStatus` out of `user` package. Not sure why I added it there (maybe cause of the name) but it clearly belongs to the higher level of abstraction.  
Other changes included:
- Implemented some utilities methods for the `SimpleController` to create common statuses with ease (less typing :tada: ).
- Added missing `USER_STATUS_INFO` code.
https://mattermost.atlassian.net/browse/MM-20825
> [MM-20825] Move UserStatus out of user package

- loadtest/user/userentity/actions.go
- loadtest/user/userentity/helper_test.go
- loadtest/user/userentity/user.go
- loadtest/user/userentity/user_test.go
PR fixes a couple of problems with error handling in the `userentity` package and adds a method to mitigate some code duplication.
It also fixes a panic (thanks @ethervoid) triggered by returning `resp.Error` directly.
https://mattermost.atlassian.net/browse/MM-20868
> [MM-20868] Improve error handling in userentity package

- example/sampleuser/user.go
- loadtest/user/user.go
- loadtest/user/userentity/actions.go
Implements userentity.CreateTeam().
The function is a simple wrapper to the underlying API call. It will be mainly used during initial data generation by a sysadmin.
https://mattermost.atlassian.net/browse/MM-20879
> [MM-20879] Implement userentity.CreateTeam()

- example/samplestore/store.go
- example/sampleuser/user.go
- loadtest/store/memstore/store.go
- loadtest/store/memstore/store_test.go
- loadtest/store/store.go
- loadtest/user/user.go
- loadtest/user/userentity/actions.go
PR implements `userentity.GetChannelMember()`.
It also re-implements how we store `ChannelMembers` data and provides related getters/setters.
https://mattermost.atlassian.net/browse/MM-20851
> [MM-20851] Implement userentity.GetChannelMember()

- example/samplestore/store.go
- example/sampleuser/user.go
- loadtest/store/memstore/store.go
- loadtest/store/memstore/store_test.go
- loadtest/store/store.go
- loadtest/user/userentity/actions.go
This PR adds  `nil` checks throughout `MemStore` implementation and related tests.
It also fixes a couple of inconsistencies with the store.
https://mattermost.atlassian.net/browse/MM-20958
> [MM-20958] Review MemStore to check against nil pointer dereferences

- example/sampleuser/user.go
- loadtest/user/user.go
- loadtest/user/userentity/actions.go
This PR adds the `GetStatus` method to the user entity. Get just use this method to test load in that endpoint mainly because the status info is passed through the websocket
https://mattermost.atlassian.net/browse/MM-21275
> Implements GetUserStatus in the user entity

- loadtest/user/userentity/user.go
- loadtest/user/userentity/websocket.go
The issue was that when the controller loop runs for the 2nd time,
the user does not login again, and the API throws "user already signed up error".
This means user.Connect does not get called. Now when it goes forward,
it calls Disconnect again during logout, essentially calling disconnect 2 times
consecutively.
This creates a panic because we call `close(ue.wsClosing)` twice consecutively.
We fix 2 bugs here:
1. We reset the channels in Connect.
2. We add a state check to indicate whether the user is disconnected/connected.
And depending on that, bail out early from the disconnect function.
https://mattermost.atlassian.net/browse/MM-21367
> MM-21367: Fix panic when Disconnect gets called consecutively

- example/loadtest.go
- example/samplecontroller/controller.go
- example/sampleuser/user.go
- loadtest/control/controller.go
- loadtest/control/simplecontroller/actions.go
- loadtest/control/simplecontroller/controller.go
- loadtest/control/simplecontroller/controller_test.go
- loadtest/control/simplecontroller/status.go
- loadtest/control/status.go
- loadtest/run.go
- loadtest/user/user.go
- loadtest/user/userentity/helper_test.go
- loadtest/user/userentity/user.go
- Removed `UserController.Init()`. The implementations should now provide their factory functions.
- Removed status parameter from `UserController.Run()`. This will be now passed during controller creation.
- Removed `Id` from `UserEntity` and added it to the controller since it is used to identify the latter.
- Removed unnecessary slice of users in `LoadTester`.
https://mattermost.atlassian.net/browse/MM-21287
> [MM-21287] Refactor UserController/User

- loadtest/user/userentity/user.go
- loadtest/user/userentity/websocket.go
There may be a case where the server is down and the websocket
keeps on trying to reconnect. In that case, if the user tries
to disconnect, the closing signal will never reach the channel.
So we used to just wait with a timeout and return. This would
leave the goroutine dangling.
A better way is to select on 2 channels, and return whenever
we get the closing signal.
> Fix indefinite wait in websocket reconnect

- cmd/loadtest/init.go
- cmd/loadtest/main.go
- config/config.default.json
- config/config.go
- example/samplestore/store.go
- example/sampleuser/user.go
- loadtest/control/simplecontroller/actions.go
- loadtest/control/simplecontroller/controller.go
- loadtest/loadtest.go
- loadtest/store/memstore/store.go
- loadtest/store/memstore/store_test.go
- loadtest/store/store.go
- loadtest/user/user.go
- loadtest/user/userentity/user.go
- loadtest/user/userentity/user_test.go
PR does add a `init` method used to insert minimal data in a MM instance needed for a load-test to run.  
Right now it simply creates a config specified number of open teams which should be enough to get us started.
PR also adds a `joinTeam` action to the `SimpleController` and a utility method `IsSysAdmin` to `UserEntity` which is needed to allow for different behaviours based on what role the user has.
https://mattermost.atlassian.net/browse/MM-20702
> [MM-20702] Implement basic init command, add joinTeam action

- loadtest/errors.go
- loadtest/loadtest.go
- loadtest/loadtest_test.go
Add appropriate mutexes necessary to guard internal state
for racy access.
https://mattermost.atlassian.net/browse/MM-21415
> MM-21415: make LoadTester API goroutine-safe

- cmd/loadtest/main.go
- loadtest/loadtest.go
- loadtest/loadtest_test.go
We add various counters and state variables to the struct
and expose them through a method.
This will help us get more information about the running load test
and store the data to be analyzed later.
While at it, we also add a AddUser/RemoveUser call in main.go
to help test race conditions. I had to do this every time manually
and thought it would be good to just keep it there.
https://mattermost.atlassian.net/browse/MM-21505
> MM-21505: implement LoadTester.Status

- example/samplecontroller/controller.go
- loadtest/control/error.go
- loadtest/control/simplecontroller/controller.go
- loadtest/control/simplecontroller/controller_test.go
- loadtest/control/simplecontroller/status.go
- loadtest/control/simplecontroller/utils.go
- loadtest/control/status.go
- loadtest/loadtest.go
- loadtest/store/memstore/random.go
- loadtest/store/memstore/random_test.go
- loadtest/store/memstore/store.go
PR adds an `ErrOrigin` field in `UserStatus` with information on the location of errors coming from `SimpleController`.
I've also modified errors string coming from the store to help identify them better.
https://mattermost.atlassian.net/browse/MM-21463
> [MM-21463] Add origin information to errors in SimpleController

- loadtest/loadtest.go
- loadtest/loadtest_test.go
Re-initialize the status channel when starting a run.
https://mattermost.atlassian.net/browse/MM-21676
> MM-21676: Fix panic on closed channel

- api/server.go
- api/server_test.go
Return an error when invalid amounts like 0, -2, "test" gets passed in the query param.
While at it, we also add some godocs and refactor the response function to include status code also so that we can pass error responses too. This is to be revamped completely in https://mattermost.atlassian.net/browse/MM-21677.
https://mattermost.atlassian.net/browse/MM-21675
> MM-21675: Return error for invalid amount

- api/server.go
- api/server_test.go
- go.mod
- go.sum
- loadtest/loadtest.go
This PR makes some minor modifications to the API that will be needed for the upcoming load agent coordinator implementation.
The most important bits:
- Switch to `/addusers` and `/removeusers` endpoints.
- Add a GET `/loadagent/{id}` endpoint.
- Make `api.APIResponse` fully JSON serializable and rename it to `api.Response`.
- Make returned messages and function names consistent.
- Make `/loadagent/create` require an `id` instead of generating one. This is particularly important so we can have better control on what we run and make everything predictable. Using `UUIDs` was not wrong but just an overkill for the current use case. I feel it's better for now to leave the `coordinator` decide how to name/identify the agents in the cluster.
https://mattermost.atlassian.net/browse/MM-21842
> [MM-21842] Improve and cleanup load-test agent API

- api/server.go
- cmd/loadtest/loadtest.go
- example/samplestore/store.go
- loadtest/control/simplecontroller/actions.go
- loadtest/store/memstore/store.go
- loadtest/store/store.go
- loadtest/user/userentity/helper_test.go
- loadtest/user/userentity/user.go
- loadtest/user/userentity/user_test.go
Right now the required information to signup a user (username, email and password) are hardcoded in the `SimpleController` implementation. This PR makes those fields configurable from the upper layer (the user of the `LoadTester` API).   
This will be particularly useful to the upcoming coordinator implementation as it will help making sure we have complete control over users and guarantee uniqueness among the whole load agent cluster.
https://mattermost.atlassian.net/browse/MM-21850
> [MM-21850] Let LoadTester API user define basic user's information

- .gitignore
- api/server.go
- api/server_test.go
- cmd/coordinator/main.go
- cmd/loadtest/init.go
- cmd/loadtest/loadtest.go
- cmd/loadtest/main.go
- cmd/loadtest/server.go
- config/coordinator.default.json
- coordinator/agent/agent.go
- coordinator/agent/config.go
- coordinator/cluster/cluster.go
- coordinator/cluster/config.go
- coordinator/cluster/status.go
- coordinator/config.go
- coordinator/coordinator.go
- loadtest/config.go
- loadtest/control/simplecontroller/actions.go
- loadtest/loadtest.go
- loadtest/loadtest_test.go
- loadtest/user/userentity/helper_test.go
This PR proposes the first draft implementation for the load-test agent coordinator. This is a separate command that will help in running a load-test across a cluster of load-test agents. It will be the main tool used when running load-tests for production. 
The implementation is made by three main components/packages:
- `coordinator` (the highest level component that handles a cluster of load-test agents and reacts to performance degradation events).
- `cluster` (the layer in charge of incrementing/decrementing the number of concurrently active users across all the available agents and provide aggregated status reports).
- `agent` (a component that acts as a simple HTTP API client that interfaces with the load-test API that we recently implemented.)
I apologize in advance for the …
> [MM-21647] First implementation for the load-test agent coordinator

- .circleci/config.yml
The created named circleCI executor is causing schema violations. Not using a named schema executor seems to fix it.
> Fix circleci schema violation. 

- loadtest/user/userentity/utils.go
- loadtest/user/userentity/utils_test.go
If we are setting 0 len with x cap, we should use append call.
If we are setting x len, we should use indices.
We were mixing the two. Fixed it now to set x len.
https://mattermost.atlassian.net/browse/MM-21900
> MM-21900: fix panic in userentity.postsMapToSlice

- cmd/loadtest/init.go
- loadtest/control/simplecontroller/actions.go
- loadtest/control/simplecontroller/controller.go
- loadtest/user/userentity/actions.go
- Create channels during the init phase.
- Populate teams and channels after login.
- Set the createAt time during creating a post, and fix the time search range
while searching for posts.
- Choose a channel randomly instead of the first channel.
- Added a viewUser action which populates the users in the store.
https://mattermost.atlassian.net/browse/MM-21897
> MM-21897: Fix failing actions in simpleController

- cmd/metricswatcher/config/config.go
- cmd/metricswatcher/metrics.go
- config/coordinator.default.json
- coordinator/cluster/cluster.go
- coordinator/config.go
- coordinator/coordinator.go
- coordinator/performance/config.go
- coordinator/performance/monitor.go
- coordinator/performance/prometheus/api.go
- coordinator/performance/prometheus/config.go
- coordinator/performance/prometheus/helper.go
- coordinator/performance/prometheus/helper_test.go
- coordinator/performance/prometheus/sample_test.go
- coordinator/performance/status.go
- coordinator/utils.go
- coordinator/utils_test.go
- loadtest/user/userentity/utils_test.go
PR implements the missing performance monitoring component by extracting some very useful code from the `metricswatcher` tool.
It also adds an initial implementation for the feedback loop that will regulate the number of concurrently active users to run.
This is all **very** experimental still. The idea is that we want to try and keep the loop as simple as possible (hard thing to do).  
I've left various comments throughout the code to explain some decisions and oversimplifications I took.
https://mattermost.atlassian.net/browse/MM-21896
> [MM-21896] Implement performance monitor and complete feedback loop

- example/sampleuser/user.go
- loadtest/control/simplecontroller/actions.go
- loadtest/control/simplecontroller/controller.go
- loadtest/store/store.go
- loadtest/user/user.go
- loadtest/user/userentity/user.go
- loadtest/user/userentity/websocket.go
- Handle USER_UPDATED and STATUS_CHANGED events.
- When a user status becomes online, send a direct message to the user
if we already have a direct channel created with that user.
- Ignore the WebSocket response channel for now because there aren't
any interesting things to do.
> MM-21559: React to websocket events

- README.md
- cmd/loadtest/init.go
- loadtest/control/simplecontroller/actions.go
- loadtest/control/simplecontroller/utils.go
- loadtest/control/simplecontroller/utils_test.go
This PR adds following:
- Initialize channels with a display name
- Avoid removing valuable info from the user name while updating
https://mattermost.atlassian.net/browse/MM-22439
> [MM-22439] - Fix channel initialization and avoid removing valuable info from the user name while updating

- loadtest/control/simplecontroller/actions.go
- loadtest/control/simplecontroller/controller.go
- During load testing, it was found that doing login/logout on every iteration has a huge CPU cost and essentially takes up the entire CPU profile. Keeping this logic would prevent us from looking into what bottlenecks do we have in the system because all of the time would be spent on hashing the user passwords.
Hence we reduce the frequency to allow other actions to be executed more frequently and allow us to look into what other parts can be optimized.
- Reordered login to be after logout in the loop
so that the frquency of logout/login can be reduced without
leaving the user in a logged out state.
- Doing logout/login once every 20 iterations of the loop.
- Doing signup and login in an initial phase before starting the loop
so that the user is in a logged in state when the loop starts. …
> MM-22101: reduce login/logout frequency

- loadtest/loadtest.go
While stopping a LoadTester, we just stopped reading from the channel
without ensuring the goroutine exited. This cause a race condition
when re-starting an existing loadtester.
We fix this by sending a quit signal which would actually exit
from the goroutine and ensure the channel read is no longer in memory.
https://mattermost.atlassian.net/browse/MM-22701
> MM-22701: Fix race in reading statusChan

- terraform/create.go
This did not get caught in https://github.com/mattermost/mattermost-load-test-ng/pull/119
because master was not yet rebased with it, where the -E flag to golangci-lint was removed.
> Fix lint error

- api/server.go
- cmd/loadtest/loadtest.go
- config/config.default.json
- coordinator/cluster/utils_test.go
- loadtest/config.go
- loadtest/loadtest.go
- loadtest/loadtest_test.go
PR will make the type of `UserController` to run during a load-test a configurable option. It also adds a configuration setting for the rate.
https://mattermost.atlassian.net/browse/MM-22893
> [MM-22893] Make UserController type to be used configurable

- example/samplestore/store.go
- loadtest/store/memstore/store.go
- loadtest/store/memstore/store_test.go
- loadtest/store/store.go
- loadtest/user/userentity/websocket.go
PR adds a handler function in `userentity` for the following WebSocket events:
- `model.WEBSOCKET_EVENT_POSTED`
- `model.WEBSOCKET_EVENT_POST_EDITED`
- `model.WEBSOCKET_EVENT_POST_DELETED`
https://mattermost.atlassian.net/browse/MM-22884
> [MM-22884] Handle post related ws events in userentity

- loadtest/control/simplecontroller/controller.go
- loadtest/control/utils.go
In rare cases, the random duration in time.Ticker be zero, and
then it would get stuck because it returns a nil channel if d <=0.
This would prevent the controller from moving forward in it's loop,
and eventually not even receive the stop signal. We fix this
by simply changing it to a time.Sleep. This is much better and also
bypasses the problem of the ticker not being garbage collected.
Fun debugging session. Moral of the story: don't try complicated things
when simple works :)
We also fix the missing case of not calling the cleanup function.
https://mattermost.atlassian.net/browse/MM-23183
> MM-23183: fix deadlock in emulateUserTyping

- terraform/cluster.tf
This gets rid of the hardcoding. A general problem still persists
where if two people use the same cluster name, then there will be a clash again.
But then the problem with adding a random string is that we need to pass the exact
same thing during destruction too.
So for now, we will recommend users to prefix the cluster names with their names
to compartmentalize deployments.
https://mattermost.atlassian.net/browse/MM-23262
> MM-23262: Use the cluster name as a prefix for keypair

- loadtest/config.go
- terraform/create.go
Overload the `MattermostDownloadURL` to have a file:// prefix
which indicates a local build. In that case, we can download everything
from a stable release, and just copy the binary from local.
https://mattermost.atlassian.net/browse/MM-22773
> MM-22773: provision a local mattermost build

- deployment/terraform/create.go
- deployment/terraform/ssh/ssh.go
The ssh agent creation would succeed even if there are no keys
added to the agent. This would lead to the deployer eventually getting stuck.
We add an additional check to list the keys first and verify that at least one
key is there.
This required the connection creation to be split up by first creating an agent
and then using that to create a connection.
https://mattermost.atlassian.net/browse/MM-23126
> MM-23126: Validate that keys are added to the ssh agent

- deployment/config.go
- deployment/terraform/create.go
- deployment/terraform/engine.go
Some general refactors which didn't fit into a ticket.
- Set `ConsoleJSON` to false from code also.
- Moved the runCommand method to a separate file as everything was being
shoved into create.go.
- Changed the updateConfig method to return an error and perform
logging only from Create.
- Removed some TODOs
- Added some logging which gives an indication as to what is happening
after a terraform deployment finishes because there's still some things
that are done from inside the code.
- Increased the command timeout to 10 minutes because RDS deployment
sometimes takes close to 4.40 minutes and when we move to cluster
deployment, it's sure going to take a lot more.
- Replaced errors.Wrap with fmt.Errorf which is used more consistently.
> General refactors for terraform

- example/samplestore/store.go
- example/sampleuser/user.go
- loadtest/control/actions.go
- loadtest/control/utils_test.go
- loadtest/store/memstore/store.go
- loadtest/store/memstore/store_test.go
- loadtest/store/store.go
- loadtest/user/user.go
- loadtest/user/userentity/actions.go
PR adds information about the current team/channel to the `memstore`.
I've also included a couple of fixes to issues with populating the store.
There might be some more places where to use `currentChannel`/`currentTeam` but I'll leave it for another PR.
https://mattermost.atlassian.net/browse/MM-23372
> [MM-23372] Add currentChannel/currentTeam in memstore

- cmd/loadtest/loadtest.go
- example/samplestore/store.go
- example/sampleuser/user.go
- loadtest/control/actions.go
- loadtest/control/simulcontroller/actions.go
- loadtest/control/simulcontroller/controller.go
- loadtest/control/simulcontroller/controller_test.go
- loadtest/control/simulcontroller/periodic.go
- loadtest/control/simulcontroller/websocket.go
- loadtest/store/memstore/random.go
- loadtest/store/memstore/store.go
- loadtest/store/store.go
- loadtest/user/user.go
- loadtest/user/userentity/actions.go
- loadtest/user/userentity/user.go
- loadtest/user/userentity/websocket.go
This PR mainly implements or refactors several actions for `SimulController` in the quest to improve the overall simulation quality.
My strategy was to begin with the most frequent API calls and try to simulate the related user behaviour as best as possible.
In the end I've decided to split this since it was becoming way too big to be easily reviewed and also was taking a lot of time.
Included in the PR are:
- Signup/Login/Logout/Reload actions.
- Action to join a team.
- Actions to switch teams/channels.
- Action to create a post.
- Actions to create direct/group channels.
- Event handler for `user_typing`.
A bit of a **note**:
`SimulController` is still under heavy development and nothing is set in stone. As you might notice I've left several `TODOs` to speed up development and avoid …
> [MM-23140] Implement actions for SimulController (part I)

- loadtest/control/simulcontroller/controller.go
If initial login failed `SimulController` would never run the websocket event handler.
This in turn would create a deadlock when the underlying ws client (in `userentity`) would be trying to write to the `wsEventChan` without anyone reading.
@agnivade spotted this when running a load-test with several (100+) users. After a call to `Stop()` the `LoadTester` would block on a certain controller (cause of the mentioned deadlock) and the rest of controllers coming after it in the slice of controllers would continue running indefinitely.
We might still need a strategy to handle the initial login failure case, maybe stop the controller completely. Need some thinking about so I'll leave it for a separate PR.
https://mattermost.atlassian.net/browse/MM-23512
> [MM-23512] Fix deadlock in SimulController

- deployment/terraform/ssh/ssh.go
Added `Start(cmd)` method to run a command w/o waiting it to finish. I can update the PR if others (e.g. `Wait`) are needed.
https://mattermost.atlassian.net/browse/MM-23565
> [MM-23565] ssh: add start command

- config/deployer.default.json
- deployment/config.go
- deployment/terraform/agent.go
- deployment/terraform/cluster.tf
- deployment/terraform/create.go
- deployment/terraform/destroy.go
- deployment/terraform/outputs.tf
- deployment/terraform/variables.tf
This PR adds loadtest agents and a coordinator while running load tests on AWS.
https://mattermost.atlassian.net/browse/MM-23450
> [MM-23450] Deploy a clustered load test agent setup using Terraform

- example/sampleuser/user.go
- loadtest/control/noopcontroller/controller.go
- loadtest/control/simplecontroller/actions.go
- loadtest/control/simulcontroller/actions.go
- loadtest/user/user.go
- loadtest/user/userentity/user.go
- loadtest/user/userentity/websocket.go
PR fixes yet another deadlock. Similarly to https://github.com/mattermost/mattermost-load-test-ng/pull/170, a failure to login would cause the ws client not to connect. When creating a post the user would still try to send the typing event regardless of the status of the connection. This would cause the user to block forever writing on the `wsTyping` channel.
PR also makes the `UserEntity.Connect()` method return an error to avoid a possible goroutine leak.
https://mattermost.atlassian.net/browse/MM-23627
> [MM-23627] Fix deadlock on SendTypingEvent()

- cmd/loadtest/loadtest.go
- loadtest/control/simulcontroller/utils_test.go
- loadtest/control/utils.go
- loadtest/control/utils_test.go
- loadtest/store/memstore/random_test.go
- loadtest/store/memstore/utils.go
This PR adds:
- Global seed when running 'loadtest`
- `TestMain` functions to be able to set rand seed. 
https://mattermost.atlassian.net/browse/MM-23225
> [MM-23225] Add ability to get seed from environment variable

- api/server.go
- cmd/loadtest/server.go
This PR removes the dependency to a config file when starting the `loadtest` in server mode. 
https://mattermost.atlassian.net/browse/MM-23536
> [MM-23536] cmd/loadtest: remove config file requirement for server mode

- loadtest/control/simulcontroller/actions.go
- loadtest/control/simulcontroller/controller.go
PR adds code to handle login failures in `SimulController` with a very simple re-try mechanism.
This will avoid having users continuously failing to run actions cause the initial login didn't succeed.
https://mattermost.atlassian.net/browse/MM-23628
> [MM-23628] Handle login failures in SimulController

- Makefile
This PR updates the `Makefile` to be able to do binary releases easier. In a nutshell, changes are:
- `make install` simply does `go install`
- The binaries and other files are now under `dist/version` (version can be either branch name or the tag)
- We make only the coordinator and the agent, default binary names are `lt-coordinator` and `lt-agent`. We may want to change :) 
https://mattermost.atlassian.net/browse/MM-23537
> [MM-23537] Update Makefile to produce binaries for the coordinator and the agent

- Makefile
Instead of packaging like: 
```
.
├── README.md
├── bin
│   ├── lt-agent
│   └── lt-coordinator
└── config
├── config.json
├── coordinator.json
└── simplecontroller.json
```
We put all files under `mattermost-load-test-ng-$(VERSION)-linux-amd64` directory:
```
mattermost-load-test-ng-$(VERSION)-linux-amd64
├── README.md
├── bin
│   ├── lt-agent
│   └── lt-coordinator
└── config
├── config.json
├── coordinator.json
└── simplecontroller.json
```
> Pack binaries under the release file name

- cmd/ltagent/init.go
- config/config.default.json
- config/simplecontroller.default.json
- example/sampleuser/user.go
- loadtest/config.go
- loadtest/control/simplecontroller/actions.go
- loadtest/control/simplecontroller/controller.go
- loadtest/control/utils.go
- loadtest/control/utils_test.go
- loadtest/user/user.go
- loadtest/user/userentity/actions.go
- loadtest/user/userentity/user.go
- We modify the init command to create users as team admins,
so that when the load test is run, some users should be able to change
team names.
- We add a new action to update the team display name and check
whether the user is a team admin or not.
- We add a new random function to randomly modify the team display name
while keeping the naming scheme consistent.
https://mattermost.atlassian.net/browse/MM-23711
> MM-23711: add update team action

- deployment/terraform/create.go
Display coordinator's instance information at the end of the deployment creation.
https://mattermost.atlassian.net/browse/MM-23715
> [MM-23715]deployment/terraform: highlight coordinator instance information

- cmd/ltagent/init.go
- cmd/ltagent/loadtest.go
- cmd/ltcoordinator/main.go
- cmd/ltctl/main.go
- coordinator/config.go
- deployment/config.go
- deployment/terraform/agent.go
- deployment/terraform/coordinator.go
- loadtest/config.go
- loadtest/user/userentity/helper_test.go
- loadtest/user/userentity/user_test.go
PR removes hard-coded config defaults from deployment code.
It also makes sure we upload configs when starting a new load-test.
I didn't implement passing the configs via command line since it requires some extra work/thinking and might get confusing passing three separate configs.
https://mattermost.atlassian.net/browse/MM-23819
> [MM-23819] Remove hard-coded config defaults from deployment related code

- .gitignore
- api/server.go
- cmd/ltagent/loadtest.go
- config/simulcontroller.default.json
- docs/simulcontroller_config.md
- loadtest/control/config.go
- loadtest/control/simulcontroller/config.go
- loadtest/control/simulcontroller/controller.go
- loadtest/control/simulcontroller/controller_test.go
PR adds configuration for `SimulController`.
It also refactors a bit the code around controllers creation to avoid doing a `ReadConfig` every time a new controller/user is created.
https://mattermost.atlassian.net/browse/MM-23648
> [MM-23648] Add config for SimulController

- Makefile
- config/config.go
- coordinator/config.go
- loadtest/config.go
- loadtest/control/simplecontroller/config.go
- loadtest/control/simulcontroller/config.go
PR adds the behaviour that the documentation mentions. If the expected config file is not found we rely on the default one.
https://mattermost.atlassian.net/browse/MM-23897
> [MM-23897] Fallback on defaults if expected config is not found

- config/simplecontroller.default.json
UpdateProfileImage performs image encoding and decoding
which takes a big toll on CPU. Running it once every iteration
nearly pegs the CPU to 100%. We reduce it to make things
a bit more normal.
> Reduce frequency of updateProfileImage

- config/coordinator.default.json
PR fixes a problem with the default config for `coordinator`.
`MaxActiveUsers` needs to be less or equal to what is configured by the load-test agent or it will fail to start with default configs.
> Fix default config for coordinator

- Makefile
In Ubuntu /bin/sh links to dash which does not support >&.
We use normal redirection. This gets rid of the
Syntax error: Bad fd number warning
> Use normal stderr redirection

- api/server.go
- example/samplestore/store.go
- loadtest/control/actions.go
- loadtest/store/memstore/store.go
- loadtest/store/memstore/store_test.go
- loadtest/store/store.go
- loadtest/user/userentity/websocket.go
PR addresses a few issues we encountered during testing that had to do with allocated memory growing very fast and eventually causing OOM crashes.
Main changes are:
- Store only new posts and reactions if they are made in the current channel.
- Changed `memstore.PostsSince` to return Ids instead of full posts.
- Added a minor optimization in `memstore.SetChannelMembers` to avoid an additional allocation.
This is a diff of heap profiles on a ltagent running 500 controllers before and after the changes in this PR.
```
Showing nodes accounting for -347.02MB, 70.39% of 493.01MB total
Dropped 142 nodes (cum <= 2.47MB)
Showing top 50 nodes out of 67
flat  flat%   sum%        cum   cum%
-124.03MB 25.16% 25.16%  -124.03MB 25.16%  reflect.New
-58.50MB 11.87% 37.02%   -62.50MB 12.68% …
```
> [MM-24019] Reduce overall memory consumption for controllers

- api/server.go
- loadtest/control/simplecontroller/controller.go
- loadtest/errors.go
- loadtest/loadtest.go
- loadtest/loadtest_test.go
PR tries to improve the time it takes to stop multiple controllers:
- Moved from a sequential approach to a concurrent approach when stopping controllers.
- Converted AddUser/RemoveUser to accept the number of users to be added/removed.
- Improved `SimpleController` early shutdown time by implementing a simple select loop for init actions.
- Improved related tests.
Some results of removing 100 users from an agent running 500:
Before:
```
$ time curl -X POST http://localhost:4000/loadagent/lt0/removeusers\?amount\=100
{"message":"100 users removed","status":{"State":"running","NumUsers":400,"NumUsersAdded":500,"NumUsersRemoved":100,"NumErrors":500,"StartTime":"2020-04-09T15:17:24.157714273Z"}}
real	2m25.001s
user	0m0.005s
sys	0m0.013s
```
After:
```
$ time curl -X POST …
```
> [MM 24018] Improve latency when stopping multiple controllers

- deployment/terraform/create.go
We hardcoded a 30 second sleep to wait server to get up. Instead of sleeping, we can ping the system endpoint and check the response to verify whether it is up or not.
https://mattermost.atlassian.net/browse/MM-23566
> [MM-23566] deployment/terraform: add server ping

- api/server.go
- api/server_test.go
- cmd/ltagent/server.go
- coordinator/agent/agent.go
- docs/local_loadtest.md
This PR adds ability to upload the specific controller's config as part of the load-test creation.
https://mattermost.atlassian.net/browse/MM-23900
> [MM-23900] api/server: accept loadtest.Config and control.Config for agent creation

- loadtest/user/userentity/websocket.go
PR fixes a bad check in case `memstore.CurrentChannel()` returns a `nil` error.
https://mattermost.atlassian.net/browse/MM-24280
> [MM-24280] Fix error check in handleReactionEvent

- api/server.go
- api/server_test.go
- loadtest/control/simulcontroller/config.go
PR fixes a bug with setting the `control.Config` interface before checking if the concrete type was `nil`.  
This would only manifest when creating and agent through the API and not passing the controller's config but relying on defaults.
https://mattermost.atlassian.net/browse/MM-24343
> [MM-24343] Fix creating/starting agent from API without controller config

- deployment/terraform/engine.go
This PR changes the log level for terraform run command to `debug` from `info`.
> deployment/terraform: switch run command log to debug

- deployment/terraform/create.go
10 minutes was getting too close for deploying big clusters.
And also for cases when we want to destroy and create clusters
in the same command.
> Bump runtime timeout to 30 minutes

- deployment/terraform/strings.go
Setting an aggresive GC rate has shown good results when the agent
is under memory pressure. So we use this to increase the longevity
of the agent.
As we can see from above, the memory climb is much slower in the second case.
> MM-24393: Set GOGC=50 for ltagent service

- config/deployer.default.json
Load test agents require much more CPU and memory than a t2.medium can provide.
Let's bump it higher.
https://mattermost.atlassian.net/browse/MM-24313
> MM-24313: Bump up instance class of agents

- deployment/terraform/create.go
The default limits are too low for load testing. Bumping them alone brings down the response time by 1/4th.
https://mattermost.atlassian.net/browse/MM-24546
> MM-24546: Bump up connection limits to DB

- loadtest/store/memstore/random.go
- loadtest/store/memstore/random_test.go
- loadtest/store/memstore/store.go
`memstore.RandomUser()` would spin indefinitely (with the `RLock` acquired) if at the time it was called the only user in the map of users was the current user (which we explicitly avoid picking by continuing).
This would immediately cause `memstore.Id()` to block waiting (we were actually calling `Lock()` instead of `RLock()` in it). The `loadtest.handleStatus` function would then block , the `statusChan` where all the controllers write to would get full and everything would eventually come to a stop.
Somehow I assumed (wrongly) that it wasn't possible to get the current user from the map of users in the store, hence the erroneous check for `len(s.users) < 1`.
I've also included a test that would have triggered the issue.
https://mattermost.atlassian.net/browse/MM-24543
> [MM-24543] Fix deadlock in memstore

- deployment/terraform/agent.go
- deployment/terraform/create.go
- deployment/terraform/strings.go
We split out the client optimizations from server optimizations
because server configs need some more help to be able to serve
connections at a high rate.
After we improved the websocket client to maintain a semaphore
for client API calls, the number of concurrent HTTP requests
increased by 8*CPU count. On a 2 core machine, this would
result in a 16x increase in connections. Therefore, when we
would have nearly 700 users, the server would be unable
to handle 11200 connections.
The nginx logs clearly showed the problem:
```
2020/04/25 09:07:11 [crit] 3642#3642: *1315161 connect() to 172.31.1.55:8065 failed (99: Cannot assign requested address) while connecting to upstream, client: 172.31.1.148, server: _, request: "POST /api
/v4/users/ids HTTP/1.1", upstream: …
```
> MM-21660: Apply advanced sysctl optimizations

- cmd/ltctl/main.go
This PR fixes a typo in the `ltctl go` subcommand.
https://mattermost.atlassian.net/browse/MM-24655
> [MM-24655] Fix valid args for ltctl go command

- loadtest/user/userentity/websocket.go
PR fixes a ws client leak in `userentity`. In case the ws event channel was getting closed we would exit the inner loop and re-create the client without explicitly closing the previous one which meant leaking the internal writer goroutine.
PR also adds a case to handle the timeout event.
https://mattermost.atlassian.net/browse/MM-24756
> [MM-24756] Fix ws client leak and handle timeout event

- deployment/terraform/info.go
- deployment/terraform/output.go
We add another helper IsEmpty to determine if a setup has any data or not.
https://mattermost.atlassian.net/browse/MM-24452
> MM-24452: fix info crash after a setup is destroyed

- deployment/terraform/strings.go
dmesg logs started showing: ip_local_port_range: prefer different parity for start/end values
According to kernel docs:
ip_local_port_range - 2 INTEGERS
>	Defines the local port range that is used by TCP and UDP to
choose the local port. The first number is the first, the
second the last local port number.
If possible, it is better these numbers have different parity
(one even and one odd value).
Must be greater than or equal to ip_unprivileged_port_start.
The default values are 32768 and 60999 respectively.
Since the ip_unprivileged_port_start is 1024, we increment the lower bound
to be the odd one. Just a random choice.
https://mattermost.atlassian.net/browse/MM-24802
> MM-24802: Fix parity of ip_local_port_range

- loadtest/store/memstore/random.go
- loadtest/store/memstore/random_test.go
PR fixes a possible deadlock in `memstore.RandomUsers()`.
It's practically the same problem we recently fixed in https://github.com/mattermost/mattermost-load-test-ng/pull/254.
We assumed the current user would not be in the map of users hence allowed for picking up to `len(s.users)` which meant that in case of `len == 2` and one of them was the current user `Randomuser()` would always the return the same user and the loop in `RandomUsers()` would spin indefinitely (with the read lock acquired) trying to get a different one.
PR also improves the logic a bit by checking whether the current user is in the store and if so decreasing by one the number of *selectable* users.
https://mattermost.atlassian.net/browse/MM-24758
> [MM-24758] Fix possible deadlock in memstore

- .golangci.yml
- go.mod
- loadtest/user/userentity/websocket.go
- websocket/client.go
- websocket/client_test.go
This is a complete rewrite of the websocket client stripping out the parts
that aren't necessary to make it a extremely simple, bare-bones and safe
implementation.
There is just one listener goroutine and nothing else. No timeouts, no ping handlers,
no response channels. No extra frills.
Writes are synchronized through a mutex and close is made synchronous by waiting
on the reader waitgroup to be done.
https://mattermost.atlassian.net/browse/MM-24910
> MM-24910: Rewrite ws client

- cmd/ltctl/main.go
When no arg provided to the `ltctl go` it will list the available detinations.
https://mattermost.atlassian.net/browse/MM-24657
> [MM-24657] cmd/ltctl: add available options for ltctl go command

- cmd/ltctl/main.go
When no arg provided for `ltctl ssh` command, it will do the same with `ltctl ssh list` command.
https://mattermost.atlassian.net/browse/MM-24656
> [MM-24656] cmd/ltctl: print list when no parameter provided for ltctl ssh cmd

- deployment/terraform/coordinator.go
- deployment/terraform/create.go
- deployment/terraform/strings.go
During starting a coordinator, we were not passing the controller
config files at all. This meant that the coordinator silently used
the default configs which were not ideal. So during coordinator start
we pass the controller files too.
While here, we also fix some other things.
- Set the /etc/security/limits.conf file on app servers too.
- Tune the read/write/connect timeouts slightly on both app and nginx.
- Set the Readonly config to true which is the default and should be set.
> MM-24930: Pass along controller config too

- api/server.go
- cmd/ltagent/init.go
- cmd/ltagent/loadtest.go
- config/simulcontroller.default.json
- loadtest/control/simulcontroller/actions.go
- loadtest/control/simulcontroller/controller.go
- loadtest/control/simulcontroller/controller_test.go
- loadtest/loadtest_test.go
- loadtest/user/userentity/helper_test.go
- loadtest/user/userentity/user.go
PR further refines actions frequencies for `SimulController` to better match those of a real user.
Data from our community servers has been used to perform the tuning.
Other notable changes included are:
- Tuned average idle time.
- Improved fetching users statuses.
- Made clients use a shared `http.Transport`. This should help improving overall connectivity performance.
- Fixed a bug with file uploads. Not sure if it was related with the errors we've been seeing server side but it's a possibility.
https://mattermost.atlassian.net/browse/MM-24688
> [MM-24688] Refine SimulController

- coordinator/agent/agent.go
- coordinator/cluster/cluster.go
We assume that a 404 is semantically the same as the agent restarted.
Therefore we create a new load test in that case.
A short log of the coordinator restarting an agent
```
info    coordinator/coordinator.go:100  coordinator: incrementing active users  {"num_users": 16}
info    cluster/cluster.go:87   cluster: adding users to agent  {"num_users": 16, "agent_id": "lt0"}
error   coordinator/coordinator.go:102  coordinator: failed to increment users  {"error": "cluster: failed to add users to agent: Post \"http://localhost:4000/loadagent/lt0/addusers?amount=16\": dial tcp 127.0.0.1:4000: connect: connection refused"}
info    coordinator/coordinator.go:76   coordinator: cluster status:    {"active_users": 112, "errors": 64}
info    coordinator/coordinator.go:85   coordinator: supported …
```
> MM-24879: Restart agents on crash

- loadtest/store/memstore/random.go
- loadtest/store/memstore/store.go
- loadtest/store/memstore/store_test.go
We were using the read lock recursively which is not allowed.
To fix this, we use a separate internal method.
https://mattermost.atlassian.net/browse/MM-24970
> MM-24970: Fix double-locking of the store

- cmd/ltagent/loadtest.go
- example/sampleuser/user.go
- loadtest/config.go
- loadtest/control/clustercontroller/controller.go
- loadtest/user/user.go
- loadtest/user/userentity/actions.go
Just a basic smoke testing of the APIs that involve cluster communication.
It just iterates over all APIs serially, rolling over to the first API.
https://mattermost.atlassian.net/browse/MM-25049
> MM-25049: Add cluster controller

- deployment/terraform/create.go
- deployment/terraform/strings.go
1024 is too high a number for it. I misunderstood the directive to be something
where nginx would only keep connections alive when the client wouid be done with them.
But this is a different set of connections than "active" ones. And it is specifically mentioned in the docs.
> It should be particularly noted that the keepalive directive does not limit the total number
of connections to upstream servers that an nginx worker process can open.
The connections parameter should be set to a number small enough to let upstream servers
process new incoming connections as well.
https://nginx.org/en/docs/http/ngx_http_upstream_module.html#keepalive
After some trial and error, I found 64 to be a decent number.
Previously timeout errors would start to appear at 1k connections, now it comes at around …
> MM-25511: Improve nginx keepalive connections

- deployment/terraform/metrics.go
- deployment/terraform/strings.go
PR reworks a bit how we group and name Prometheus targets. This is to facilitate certain queries and at the same time make it easier to manually filter data in Grafana.
For example, I couldn't find a way to query node-exporter data coming only from app instances.
Now it's possible with a simple regexp on the `instance` label.
https://mattermost.atlassian.net/browse/MM-25532
> [MM-25532] Make Prometheus targets human friendly

- coordinator/cluster/cluster.go
While shutting down a huge cluster of more than 10k users,
the stopping of the coordinator service will time out, leading
to the service being forcibly killed but the agents would still
be running.
We shutdown in parallel to reduce the time.
The DefaultTimeoutStopSec is 90 seconds, so we can keep that as is.
https://mattermost.atlassian.net/browse/MM-25437
> MM-25437: Shutdown agents in parallel

- loadtest/control/simulcontroller/actions.go
- loadtest/control/simulcontroller/controller.go
- loadtest/store/memstore/store.go
- loadtest/user/userentity/actions.go
PR implements a simple re-try mechanism for SimulController's init actions. If an action fails we'll run it again until it does.
Sometimes it would happen than an init action failed for some user and the controller would keep running with an inconsistent state (no sufficient data) which meant that while the user was considered active it would not apply the desired load and instead return errors.
Included in the PR are also other bug fixes which caused either crashes (nil dereferencing panics) or state errors (e.g. current team not set).
https://mattermost.atlassian.net/browse/MM-25410
> [MM-25410] Re-try failed init actions in SimulController

- loadtest/user/userentity/user.go
Without a timeout in the HTTP request, the underlying TCP dialer
timeouts were also not working. And basically the entire network
stack would be dysfunctional.
https://mattermost.atlassian.net/browse/MM-25605
> MM-25605: Add timeout to the HTTP client

- loadtest/control/simulcontroller/utils.go
- loadtest/control/simulcontroller/utils_test.go
- loadtest/user/user.go
- Skip common username prefix when loadtesting typed mentions. 
- https://mattermost.atlassian.net/browse/MM-25424
> MM-25424: skip common prefix when considering mentioning username

- config/config.default.json
- config/coordinator.default.json
PR sets the default controller to `simulative` and also changes the default for max active users.
These values come from several tests and they apply to default configs.  Currently I've verified the following:
```golang
map[string]int{
"t3.xlarge": 2000,
"m5.xlarge": 2500,
"m5.2xlarge": 4500,
}
```
These are the maximum number of user to be ran on a single agent instance of that type.
When I have gathered more data I'll also include this info in the documentation.
https://mattermost.atlassian.net/browse/MM-24613
> [MM-24613] Update some defaults

- loadtest/control/simulcontroller/utils.go
- loadtest/control/simulcontroller/utils_test.go
- Fix usage of `rand.Intn` to stop panic. Refactored to make testable.
- https://mattermost.atlassian.net/browse/MM-25850
> MM-25850: fix rand usage to not panic

- config/coordinator.sample.json
- config/deployer.sample.json
- docs/local_loadtest.md
- docs/terraform_loadtest.md
- loadtest/config.go
PR reviews the documentation, adds missing `-n` flag when running load-test manually and simplifies a bit the commands (no need to explicitly pass configs).
PR also fixes a couple of config defaults.
https://mattermost.atlassian.net/browse/MM-26034
> [MM-26034] Review docs and fix some config defaults

- api/server.go
- cmd/ltagent/init.go
- cmd/ltagent/loadtest.go
- config/config.sample.json
- coordinator/cluster/utils_test.go
- defaults/set.go
- defaults/validate.go
- deployment/terraform/agent.go
- loadtest/config.go
- loadtest/control/gencontroller/config.go
- loadtest/loadtest_test.go
PR improves current `init` process by leveraging `GenController`.
This will give us more control on the initial data to populate when creating a deployment.
https://mattermost.atlassian.net/browse/MM-25899
> [MM-25899] Use gencontroller to improve init process

- deployment/config.go
- deployment/terraform/create.go
- We validate whether an URL starts with the proper scheme.
- And we also raise an error if the mattermost download URL is not a binary
if it's a file. This fixes a common confusion where people pass paths to the entire
mattermost .tar.gz package.
https://mattermost.atlassian.net/browse/MM-25935
> MM-25935: validate the scheme prefix of download URLs

- deployment/terraform/metrics.go
This is to avoid a full round-trip across the public internet.
https://mattermost.atlassian.net/browse/MM-25936
> MM-25936: use Prometheus private IP for Grafana

- coordinator/coordinator.go
- coordinator/math.go
- coordinator/math_test.go
- coordinator/utils.go
- coordinator/utils_test.go
PR improves coordinator's feedback loop by finding an equilibrium point through simple linear regression. 
The idea is to check when the slope of the number of active users' graph flattens out.
When this value goes under a defined threshold we stop the coordinator and calculate an estimate (simple average) of the number of supported users.
https://mattermost.atlassian.net/browse/MM-26178
> [MM-26178] Improve coordinator's feedback loop

- cmd/ltctl/report.go
- config/deployer.sample.json
- defaults/json.go
- deployment/config.go
- docs/deployer_config.md
- loadtest/report/generate.go
- loadtest/report/generate_test.go
This PR changes the graph queries from being hardcoded
to being loadable from config. This takes care of using custom labels
for the queries and at the same time, use any custom query that the user
wants to run.
We also add a Label field for the Avg and P99 queries.
While here, we fix an unrelated bug that did not close the file.
Docs are updated and sample config file is also changed.
https://mattermost.atlassian.net/browse/MM-26416
> MM-26416: move Prometheus queries to load from config

- loadtest/report/compare.go
- loadtest/report/output.go
Right now, we are calculating diff from the original value, but printing rounded off values.
That shows confusing output as the diff and the values don't match up.
This PR changes that to show proper time units in duration rounded off to ms.
This changes
```
ChannelStore.GetMembersForUser |  Avg| 0.002| 0.002 | 0.000 | 3.116
| |  P99| 0.008| 0.008 | 0.001 | 7.457
| ChannelStore.GetPinnedPostCount |  Avg| 0.000| 0.000 | -0.000 | -2.957
| |  P99| 0.005| 0.005 | -0.000 | -0.043
| ChannelStore.GetPublicChannelsForTeam |  Avg| 0.001| 0.001 | -0.000 | -2.145
| |  P99| 0.005| 0.005 | -0.000 | -0.246
```
to
```
| ChannelStore.GetMembersForUser |  Avg| 2ms| 14ms | 12ms | 85.714
| |  P99| 8ms| 340ms | 332ms | 97.647
| ChannelStore.GetPinnedPostCount |  Avg| 0s| 2ms | 2ms | 100.000
| |  P99| 5ms| …
```
> MM-26421: calculate diff after rounding off

- cmd/ltcoordinator/main.go
- coordinator/agent/agent.go
- coordinator/agent/config.go
- coordinator/cluster/cluster.go
- coordinator/cluster/config.go
- coordinator/cluster/utils_test.go
- coordinator/coordinator.go
- deployment/terraform/coordinator.go
- docs/coordinator_config.md
PR simplifies `coordinator`'s config by removing the `loadtest.Config` from the `LoadAgentClusterConfig`.
The config is instead passed once when creating a new coordinator.
https://mattermost.atlassian.net/browse/MM-26395
> [MM-26395] Simplify coordinator's config

- deployment/terraform/agent.go
If there is already a .tar.gz file present, then this throws an error
while trying to move the directory. We therefore delete everything with that name.
> Remove everything with mattermost-load-test-ng in agent creation

- api/agent.go
- api/agent_test.go
- api/coordinator.go
- api/coordinator_test.go
- api/server.go
- cmd/ltagent/init.go
- cmd/ltagent/loadtest.go
- cmd/ltapi/main.go
- cmd/ltcoordinator/main.go
- coordinator/agent/agent.go
- coordinator/cluster/cluster.go
- coordinator/cluster/utils_test.go
- coordinator/coordinator.go
- coordinator/coordinator_test.go
- coordinator/performance/monitor.go
- loadtest/loadtest.go
- loadtest/loadtest_test.go
- logger/logger.go
PR splits logging for the two main components. 
This is needed to avoid having a single `ltapi.log` file with everything inside.
https://mattermost.atlassian.net/browse/MM-26459
> [MM-26459] Split logs for agent and coordinator

- api/agent.go
- api/agent_test.go
- api/coordinator.go
- api/coordinator_test.go
- api/server.go
PR makes concurrent access to API server's resources safe by storing them in a `sync.Map`.
https://mattermost.atlassian.net/browse/MM-26218
> [MM-26218] Make HTTP API resources safe for concurrent access

- api/coordinator.go
- cmd/ltctl/loadtest.go
- cmd/ltctl/main.go
- coordinator/cluster/status.go
- coordinator/coordinator.go
- coordinator/status.go
- deployment/terraform/coordinator.go
PR adds a `ltctl loadtest status` command that shows the status of the current load-test, if any.
It essentially removes the need to go through coordinator's logs to figure out what's going on.
https://mattermost.atlassian.net/browse/MM-26561
> [MM-26561] Implement loadtest status command

- docs/deployer_config.md
PR makes more explicit the fact that when using `file://` we only replace the server's binary and not the full build.
https://mattermost.atlassian.net/browse/MM-24654
> [MM-24654] Make docs more explicit

- cmd/ltctl/collect.go
- coordinator/cluster/cluster.go
- coordinator/coordinator.go
- coordinator/performance/config.go
- coordinator/performance/monitor.go
- defaults/validate.go
- deployment/config.go
- deployment/terraform/agent.go
- deployment/terraform/create.go
- deployment/terraform/ssh/ssh.go
- deployment/terraform/utils.go
- loadtest/control/simulcontroller/actions.go
- loadtest/control/simulcontroller/websocket.go
- loadtest/user/userentity/websocket.go
Courtesy of:
```sh
for file in $(rg "fmt.Errorf\(\".+\"\)" -l); do sed -r -i "s/fmt.Errorf\((\".+\")\)/errors.New(\1)/g" $file; done;
```
https://mattermost.atlassian.net/browse/MM-23914
> [MM-23914] Prefer errors.New over fmt.Errorf for simple strings

- loadtest/user/userentity/websocket.go
PR fixes a deadlock in which `userentity.SendTypingEvent()` would block until a websocket connection was established.
It's not a new one but simply required ws connections to fail in order to trigger. I've reproduced it by using a wrong ws connection URL. 
I believe this is what happened during our recent Cloud test when I had to forcefully restart the API server.
https://mattermost.atlassian.net/browse/MM-26690
> [MM-26690] Fix deadlock in SendTypingEvent

- cmd/ltctl/collect.go
- cmd/ltctl/main.go
- cmd/ltctl/report.go
- cmd/ltctl/reset.go
- deployment/terraform/engine.go
- docs/terraform_loadtest.md
PR adds a `loadtest reset` command to `ltctl` to help resetting the target instance's db and re-initialize the data.
https://mattermost.atlassian.net/browse/MM-26443
> [MM-26443] Implement loadtest reset command

- loadtest/loadtest.go
This PR adds a reset to idle controllers after stopping the `LoadTester`. My initial idea was to keep them for reuse at re-running but it was going to add too much of complexity to keep alive the `statusChan`. If it is required I probably have a branch for that :)
https://mattermost.atlassian.net/browse/MM-26694
> [MM-26694] loadtest: remove idle users after loadtester has stopped

- deployment/terraform/coordinator.go
During `ltctl loadtest start` we check if the coordinator exists and if its done we print its status and re-create it.
https://mattermost.atlassian.net/browse/MM-26863
> [MM-26863] Re-create coordinator if previous is done

- api/agent.go
- api/agent_test.go
- api/client_test.go
- api/coordinator.go
- api/coordinator_test.go
- api/server.go
PR fixes a couple of high level race conditions with creating/destroying API resources:
Trying to create a resource with the same id concurrently could cause more than one to be created.
This should be the last known race condition hence closing the investigation ticket with it.
```sh
curl -d "{\"CoordinatorConfig\": $(cat config/coordinator.json),\"LoadTestConfig\": $(cat config/config.json)}" http://localhost:4000/coordinator/create\?id\=ltc0 &
curl -d "{\"CoordinatorConfig\": $(cat config/coordinator.json),\"LoadTestConfig\": $(cat config/config.json)}" http://localhost:4000/coordinator/create\?id\=ltc0 &
curl -d "{\"CoordinatorConfig\": $(cat config/coordinator.json),\"LoadTestConfig\": $(cat config/config.json)}" http://localhost:4000/coordinator/create\?id\=ltc0 &
curl -d …
```
> [MM-23496] Fix race conditions when creating/destroying API resources

- cmd/ltctl/main.go
- cmd/ltctl/reset.go
- deployment/terraform/metrics.go
- docs/compare.md
PR addresses a couple of remaining issues causing sporadic errors.
- Checking for Grafana to be up before updating the preferences.
- Restarting all the MM app servers after a DB reset and wait until they are up before continuing.
As a bonus feature, PR also adds `--confirm` flag to the `reset` command.
https://mattermost.atlassian.net/browse/MM-27024
> [MM-27024] Fix some remaining flakiness

- config/deployer.sample.json
- deployment/config.go
- deployment/terraform/create.go
Release **1.0.0** is up at https://github.com/mattermost/mattermost-load-test-ng/releases/tag/v1.0.0
PR updates related code references.
> Releasing v1.0.0

- deployment/terraform/create.go
Executable file check suddenly failed today. My `mattermost` binary was `0755` instead of the required `0775`.
PR makes it so that we only require executable bit for owner and group to be present.
> Improve executable file check

- defaults/validate.go
- defaults/validate_test.go
Add valid values to the error for `oneof` check.
>  defaults/validate: print valid values for oneof check

- config/coordinator.sample.json
- coordinator/performance/monitor.go
- coordinator/performance/prometheus/config.go
PR is an alternative approach to fix the issue that https://github.com/mattermost/mattermost-load-test-ng/pull/377 was addressing.
We introduce a new query specific config value `MinIntervalSec` that defines the minimum amount of time (in seconds) that needs to have passed before attempting to run the query.
https://mattermost.atlassian.net/browse/MM-27906
> [MM-27906] Fix inconsistencies when querying metrics

- loadtest/control/simulcontroller/actions.go
- loadtest/control/simulcontroller/utils.go
PR fixes `SimulController.createMessage()` so that it won't fail if user mention could not be constructed.
We should still support posts with mentions of users not in the channel.
https://mattermost.atlassian.net/browse/MM-28497
> [MM-28497] Avoid failing if user mention cannot be autocompleted

- Makefile
Took a good look at this and while I can't explain why this issue hasn't occurred before (my local system never matched versions with the AWS AMI used to run load-tests) it seems that `CGO_ENABLED` is set to 1 by default (more info at https://golang.org/cmd/cgo/) if the host `GOOS` and `GOARCH` are the same as the target build. You can probably check it yourself by running ```GOOS=linux GOARCH=amd64 go env | grep CGO_ENABLED```.
PR forces cross-compilation by setting `CGO_ENABLED=0` which fixes the GLIBC version mismatch issue.
I've also taken a look at a couple other Golang projects and they all have this set to 0 as well when building releases.
> Force cross-compilation to fix GLIBC versions mismatch error

- coordinator/coordinator.go
- loadtest/control/simulcontroller/actions.go
PR fixes an issue with the coordinator failing to set the total errors count once done.
This would result in `ltctl loadtest status` showing zero errors at the end of a load-test.
https://mattermost.atlassian.net/browse/MM-29276
> [MM-29276] Set correct error count when done

- config/deployer.sample.json
- coordinator/performance/prometheus/helper.go
- loadtest/report/output.go
PR helps the performance analysis of a comparative load-test by:
- Including more insightful queries in the default config.
- Sorting the results by the amount of change (`deltaPercent`) and grouping them in improved/worsened lists.
<details><summary>Example output</summary>
| | | Base | Actual | Delta | Delta % |
| --- | --- | --- | --- | --- | --- |
| ChannelStore.UpdateLastViewedAt |  avg| 4ms| 8ms | 4ms | 114.274
| ChannelStore.IncrementMentionCount |  avg| 4ms| 8ms | 4ms | 112.415
| SessionStore.GetSessionsWithActiveDeviceIds |  avg| 1ms| 2ms | 1ms | 81.041
| PreferenceStore.Get |  avg| 1ms| 2ms | 1ms | 76.054
| TeamStore.GetByName |  avg| 1ms| 2ms | 1ms | 73.547
| PreferenceStore.GetAll |  avg| 1ms| 2ms | 1ms | 72.197
| SessionStore.GetSessionsExpired |  avg| 2ms| 3ms | 1ms | 42.930 …
> [MM-29800] Improve load-test comparisons

- coordinator/coordinator_test.go
- coordinator/performance/config.go
PR removes a check not allowing for an empty queries array in coordinator's config.
This was a purely config validation detail since `performance.Monitor` will simply range over the queries so it will not cause any real issue to have that empty/nil and it's something that makes sense in case of a bounded load-test where no feedback loop is needed.
> Accept empty queries in coordinator's config

- loadtest/config.go
PR fixes an issue with the validation of `loadtest.UserControllerConfiguration` which would fail when some percentages were set to zero.
https://mattermost.atlassian.net/browse/MM-30320
> [MM-30320] Fix validation for UserControllerConfiguration

- coordinator/coordinator.go
- coordinator/coordinator_test.go
We were failing to set the `StopTime` when the `coordinator` was explicitly stopped (e.g. during a bounded load-test).
https://mattermost.atlassian.net/browse/MM-30326
> [MM-30326] Fix empty StopTime in coordinator.Status

- loadtest/control/simulcontroller/controller.go
We remove the final `logout` action when stopping a `SimulController`. 
This was causing an enormous spike in server response times which was skewing metrics and making them less readable overall.
It was originally introduced to avoid keeping many old sessions in the DB but that's not really an issue anymore since we end up resetting the DB during comparisons.
> Remove final logout on SimulController stop

- cmd/ltctl/loadtest.go
PR adds a connected users count to the output of `ltctl loadtest status`. This can further help to identify possible issues with the load-test.
https://mattermost.atlassian.net/browse/MM-30332
> [MM-30332] Add connected users count to coordinator status output

- docs/setups.md
PR adds a document with some information about commonly tested setups, results and some important notes and gotchas.
As far as results, I've only listed the unbounded ones as they are easily expressible with a number.
In parallel to this my plan is to work on storing comparison results in a machine friendly format (JSON or similar) and start building an archive from which we could derive, generate and automatically keep up to date more documents like this.
As usual, let me know of anything you'd like to be added to this.
https://mattermost.atlassian.net/browse/MM-29243
> [MM-29243] Add some info on commonly tested setups

- loadtest/control/simulcontroller/actions.go
- loadtest/control/simulcontroller/controller.go
PR attempts to lower the server side performance impact of the initial signup/login sequence.
This is done by first attempting a login and then try to signup if the account does not exist.
This will avoid having the server do password hashing every time a controller starts.
https://mattermost.atlassian.net/browse/MM-30333
> [MM-30333] Avoid unnecessary sign-up attempts in SimulController

- api/agent.go
- docs/loadtest_config.md
- examples/loadtest/samplestore/store.go
- go.mod
- loadtest/config.go
- loadtest/control/simulcontroller/actions.go
- loadtest/control/simulcontroller/controller.go
- loadtest/control/utils.go
- loadtest/control/utils_test.go
- loadtest/store/memstore/store.go
- loadtest/store/store.go
PR adds simple versioning support for `SimulController` actions.
This is done by adding a `minServerVersion` field to the user action struct and compare that with the provided server version which is either loaded from config or directly fetched from the target MM server.
https://mattermost.atlassian.net/browse/MM-30951
> [MM-30951] Add versioning support for SimulController actions

- cmd/ltctl/comparison.go
- cmd/ltctl/main.go
- comparison/comparison.go
- comparison/config.go
- comparison/deployment.go
- comparison/output.go
PR improves the output of an automated comparison by adding information about the deployment used.
It also improves the `ltctl comparison run` command by:
- Providing a new `json` output format for the comparison results.
- Providing an option to output a `zip` archive with all the artifacts (graphs, reports) included.
https://mattermost.atlassian.net/browse/MM-30796
> [MM-30796] Improve automated comparison output

- api/agent.go
- cmd/ltagent/init.go
- cmd/ltagent/loadtest.go
- config/config.sample.json
- coordinator/cluster/cluster.go
- docs/loadtest_config.md
- loadtest/config.go
This extends the load-test functionality to read
user credentials from an external file and then
use them in the load-test.
This is helpful to simulate LDAP users which weren't possible
in the existing load-test framework
https://mattermost.atlassian.net/browse/MM-31367
> MM-31367: Support custom credential file

- api/agent.go
- loadtest/loadtest.go
- loadtest/loadtest_test.go
Added a sanity check on `MaxActiveUsers` with `Rlimit`
Fixed a `defer` bug in testing - inside `TestRemoveUsers`
Changed the static `max connections in HTTP pool` to be dynamic
JIRA - https://mattermost.atlassian.net/browse/MM-30334
Closes https://github.com/mattermost/mattermost-server/issues/16284
> [MM-30334] Add file descriptors limit Sanity Check to the Agent

- cmd/ltctl/main.go
- deployment/terraform/utils.go
- docs/terraform_loadtest.md
Support the following extra `ltctl ssh` targets: `loadtest-proxy` (or just `proxy`), `loadtest-metrics` (or just `metrics`, `grafana`, or `prometheus`).
None.
> ltctl ssh: extra targets

- cmd/ltctl/loadtest.go
- comparison/comparison.go
- comparison/loadtest.go
- deployment/terraform/agent.go
- deployment/terraform/coordinator.go
- deployment/terraform/create.go
- deployment/terraform/destroy.go
- deployment/terraform/engine.go
- deployment/terraform/info.go
- deployment/terraform/metrics.go
- deployment/terraform/output.go
PR addresses the unhelpful spam of logs returned by the comparison process.
Mostly was due to terraform initialization when performing coordinator's commands (start/stop/getstatus).
To fix this I've decoupled the logic a bit and cached the terraform outputs from the deployments.
https://mattermost.atlassian.net/browse/MM-32270
> [MM-32270] Limit terraform re-initialization during comparisons

- cmd/ltctl/reset.go
We were doing this elsewhere but missed out on this one. Without this,
the only error message we get is "exit code 1", and the actual command error
is missed out.
https://mattermost.atlassian.net/browse/MM-32747
> MM-32747: Display command output from ssh commands during ltctl reset

- comparison/loadtest.go
- deployment/config.go
- deployment/terraform/create.go
PR replaces the `mattermost reset` CLI command during automated comparisons.
The main reason behind the change is that the `reset` command can cause unnecessary delays during store initialization.
https://mattermost.atlassian.net/browse/MM-32670
> [MM-32670] Replace reset CLI command during automated comparisons

- deployment/terraform/strings.go
Adding the HTTP version to correctly perform the WS upgrade when behind NGINX.
https://mattermost.atlassian.net/browse/MM-33009
> [MM-33009] Use HTTP 1.1 for NGINX ws upgrade

- deployment/terraform/metrics.go
- deployment/terraform/strings.go
It was getting annoying to always login. We are not protecting the instance in the first place so the login is just in the way of accessing the data.
> Disable Grafana login

- loadtest/control/simulcontroller/actions.go
We check for the length of the channel name before searching for it, and if it exceeds the channel name length, we trim it to the max length.
https://mattermost.atlassian.net/browse/MM-33228
> MM-33228: Fix searchChannel for short channel names

- deployment/terraform/create.go
- deployment/terraform/strings.go
In response to https://github.com/mattermost/mattermost-server/pull/16763 we ignore the `Cache-Control` directive so that we can keep doing caching for users profile images. PR also refactors a bit the config to avoid unnecessary repetitions.
https://mattermost.atlassian.net/browse/MM-33923
> [MM-33923] nginx: ignore Cache-Control directive for getProfileImage requests

- deployment/terraform/create.go
The notification console logs still defaulted to debug which flooded
the journal logs. Taming it down to be the same as the application logs.
https://mattermost.atlassian.net/browse/MM-34079
> MM-34079: Improve notificationLog settings

- cmd/ltctl/main.go
- deployment/terraform/utils.go
Often we just need to run some commands like restarting mattermost,
or backing up a DB before a test.
Logging in every time, and running the command needs an extra step.
This makes things a bit easier.
https://mattermost.atlassian.net/browse/MM-34289
> MM-34289: Run ssh command

- examples/loadtest/samplestore/store.go
- loadtest/control/simulcontroller/actions.go
- loadtest/store/memstore/store.go
- loadtest/store/store.go
- loadtest/user/userentity/actions.go
Similarly to what happens on the web client, we want to send the ws typing event only if enabled on server.
https://mattermost.atlassian.net/browse/MM-34268
> [MM-34268] Respect server config when sending typing event

- loadtest/control/simulcontroller/actions.go
- loadtest/store/memstore/store.go
- loadtest/store/memstore/store_test.go
PR fixes a possible crash due to `nil` pointer dereference. 
It also addresses the underlying issue that was causing the returned channel stats to be `nil`.
https://mattermost.atlassian.net/browse/MM-34673
> [MM-34673] Fix nil pointer dereference crash in SimulController

- loadtest/store/memstore/random.go
- loadtest/store/memstore/random_test.go
At times the controllers would be trying to run actions on system messages which would fail. PR implements the necessary changes to filter out posts not directly created by users (where `Posts.Type` is set). This was already correctly handled by `memstore.RandomPostForChannelByUser()` but not by other post picking methods, hence this PR.
This is also the last fix I was planning before releasing 1.3.0 
https://mattermost.atlassian.net/browse/MM-34719
> [MM-34719] Filter out system messages when randomly picking posts

- cmd/ltctl/comparison.go
- comparison/comparison.go
We were saving only the comparison results and missing the deployment info which are quite useful for historical purposes.
Also added a sync operation on destroy which helps in certain cases where the deployment has been modified by hand.
> Fix comparison output

- loadtest/control/simulcontroller/actions.go
The type assertion would fail if the server wasn't available,
which would result in a panic.
panic: interface conversion: error is *url.Error, not *model.AppError
We avoid that by checking the result first.
After that:
```
{"timestamp":"2021-10-15 11:25:19.950 +05:30","level":"error","msg":"control.SignUp loadtest/control/actions.go:47 Post \"http://localhost:8065/api/v4/users\": dial tcp 127.0.0.1:8065: connect: connection refuse
d","caller":"loadtest/loadtest.go:57","controller_id":8,"user_id":""}
```
> Prevent panic in case of server offline

- loadtest/control/simulcontroller/actions.go
Previously, this was just hardcoded to false which
made it skip the CRT code paths. Now we actually
get the param from the store and pass that onwards.
https://mattermost.atlassian.net/browse/MM-41499
> MM-41499: Use CRT switch in GetTeamsUnread

- loadtest/control/actions.go
We get channels for the user only after the curren team is set.
Without that a newly signed up user won't be part of any channels
unless they join a team first.
> Fix channel switcher bug

- deployment/terraform/create.go
- In https://github.com/mattermost/mattermost-server/pull/19441 we set `ServiceSettings.ThreadAutoFollow` to `false` by default. The terraform deployment sets `ServiceSettings.CollapsedThreads` to `default_on`. ThreadAutoFollow needs to be true for CollapsedThreads to be on. In my tests, Terraform deployments were failing because the mattermost app wouldn't start because the mattermost config was in an inconsistent state. This change explicitly sets `ThreadAutoFollow` to `true`.
- N/A
> Set ThreadAutoFollow to true explicitly for terraform

- loadtest/control/simulcontroller/actions.go
PR fixes a possible panic due to wrong variable assignment.
https://mattermost.atlassian.net/browse/MM-43618
> [MM-43618] Fix possible panic in SimulController.updateThreadRead

- loadtest/store/memstore/store.go
PR fixes a possible nil pointer dereference as `MemStore.Channel()` can return `nil, nil`.
https://mattermost.atlassian.net/browse/MM-43619
> [MM-43619] Fix potential panic in `(*MemStore).MarkAllThreadsInTeamAsRead`

- api/client_test.go
- api/coordinator_client_test.go
- api/coordinator_test.go
- coordinator/coordinator_test.go
- coordinator/performance/config.go
Not sure if this is the right solution or not but the default coordinator config failed on:
```
Error: failed to create coordinator: coordinator: coordinator api request error: could not create coordinator: could not validate configuration: Description is empty
```
if I didn't copy the sample coordinator config during the steps [here](https://github.com/mattermost/mattermost-load-test-ng/blob/master/docs/terraform_loadtest.md#optionally-configure-coordinator-and-load-test) which says it's optional to do.
The other option would be to add some of the queries from the sample in the code as a default.
> Remove blank query from coordinator default config

- docs/local_loadtest.md
- docs/terraform_loadtest.md
Some minor doc updates from my experience running the ng load tests for the first time:
* After running through the set up and how to run the load test I didn't immediately no where to look to view results of my test - so added a quick link to the compare doc at the bottom of the setup docs to smooth that out a bit
* Terraform 0.14 took a bit of digging for me to find so I linked it directly - once we have a new perf owner getting this updated to latest terraform versions might be a good idea
* For staff, added a link to the Vault documentation that details how to get AWS credentials since that's not something everyone on the feature teams uses all the time
* My editor killed a bunch of whitespace
> Minor doc additions to smooth process for first time users

- docs/terraform_loadtest.md
PR updates the Mattermost employee/staff member process to generate AWS credentials from the (legacy) Vault method to using AWS Single Sign-On
Related to thread on Community: https://community.mattermost.com/core/pl/ei3yydgu6ibkfxs6wxjfgnfmpo
> Change Vault instruction to AWS Single Sign-On

- config/deployer.sample.json
- deployment/config.go
Created running
```sh
NEXT_VER=v1.6.0 make prepare-release
```
--
> Bump version to v1.6.0

- Makefile
Use go install instead of the bash pipe, and checkout and pull master to ensure that the process starts from a good state.
--
> Polish release rule in Makefile

- api/coordinator_test.go
- coordinator/cluster/config.go
- coordinator/coordinator.go
Validate UsersConfig.MaxActiveUsers is not less than clusterConfig.MaxActiveUsers
Github: https://github.com/mattermost/mattermost-server/issues/19676
JIRA: https://mattermost.atlassian.net/browse/MM-42253
> add config validation in coordinator for MaxActiveUsers

- .gitignore
- Makefile
Trying to ignore the binaries named `ltagent`, `ltapi` and `ltcoordinator`, we ended up ignoring the whole directories `cmd/ltagent/`, `cmd/ltapi/` and `cmd/ltcoordinator/`, since a line in .gitignore without any slashes matches both files and directories. It seems we have not tried to add *new* files to those directories since we ignored those files [two years ago](https://github.com/mattermost/mattermost-load-test-ng/pull/275), and since the current files there were created before .gitignore contained these matches, this problem has not been detected until now. 
The way I detected it is through a bug in my editor, which was not showing any file under those directories because they were matched by .gitignore, even if git was tracking all files there since before they were added to …
> Do not ignore lt{agent,api,coordinator}/ dirs

- api/agent.go
- cmd/ltctl/comparison.go
- cmd/metricswatcher/prometheushealthcheck/healthprovider.go
- deployment/terraform/create.go
- deployment/terraform/metrics.go
- deployment/terraform/utils.go
- loadtest/report/generate.go
- loadtest/report/output.go
- loadtest/report/output_test.go
This pr replaces deprecated `ioutil` package usages with corresponding functions in `os` and `io` packages.
Also, there are 3 generated bindata.go files still uses `ioutil`, I am not sure about what to with those.
Fixes https://github.com/mattermost/mattermost-server/issues/21479
> MM-47828: Replace deprecated ioutil package

- deployment/terraform/create.go
- deployment/terraform/engine.go
- docs/comparison.md
- docs/terraform_loadtest.md
It turns out that v1.0 is [basically the same](https://developer.hashicorp.com/terraform/language/v1.1.x/upgrade-guides/1-0) as v0.15. That, along with [Terraform v1.x compatibility promises](https://developer.hashicorp.com/terraform/language/v1-compatibility-promises) makes it so that updating from v0.15 to the latest version, v1.3.3, is just a matter of bumping the supported version.
The only real change in this PR is that the supported version is now actually a minimum supported version, which is now stored under the hood as a `semver` instead of a float.
I've tested this the same way I did with the bump to v0.15:
- Running a normal load test with:
- `go run ./cmd/ltctl deployment create`
- `go run ./cmd/ltctl deployment sync`
- `go run ./cmd/ltctl loadtest start`
- `go run ./cmd/ltctl …
> MM-47262: Bump to v1.3.3

- loadtest/control/simulcontroller/controller.go
The weight of the Insights feature action in the load-test tool was a random value. This PR adjusts it based on data from Community.
I computed the ratio between the number of calls to `getTopChannelsForTeamSince` and the number of calls to `createPost` (and a bunch of others) at two times:
- Yesterday, Wednesday Oct 26, right after an hour of peak traffic (15:00-16:00 UTC)
- Today, Thursday Oct 27, right after an hour of peak traffic (15:00-16:00 UTC)
As you can see in the values in the table, we have two similar ratios: 0.0083 and 0.00654. Given that the weight of the action to create a post is 1.5, we have a range of weights for the Insights feature: 0.00981, 0.01245. The average of those two values is 0.01113. Simplifying this value (the data we're working with is just a sample of all …
> MM-47539: Adjust frequency of insights based on Community

- config/deployer.sample.json
- deployment/config.go
Bump version to v1.7.0. PR created with `make pre-release`.
--
> Bump version to v1.7.0

- cmd/ltctl/comparison.go
- cmd/ltctl/main.go
- cmd/ltctl/report.go
- comparison/comparison.go
- comparison/deployment.go
- comparison/output.go
- deployment/terraform/create.go
Now that `terraform.New` always dereferences `cfg`, it's safer to pass it by value. This PR fixes errors such as:
```
❯ go run ./cmd/ltctl ssh
Available instances:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x258 pc=0xb90910]
goroutine 1 [running]:
github.com/mattermost/mattermost-load-test-ng/deployment/terraform.New({0x0, 0x0}, 0x0)
/home/alejandro/projects/mattermost/mattermost-load-test-ng/deployment/terraform/create.go:57 +0x30
main.RunSSHListCmdF(0xf3da60?, {0xc000010018?, 0xc000a33c50?, 0x1?})
/home/alejandro/projects/mattermost/mattermost-load-test-ng/cmd/ltctl/main.go:74 +0x34
main.main.func1(0xc0000ccf00?, {0x16f0da0?, 0x0, 0x0})
/home/alejandro/projects/mattermost/mattermost-load-test-ng/cmd/ltctl …
```
> MM-48193: Get a cfg value in terraform.New, not a pointer

- Makefile
- docs/developing.md
The PR includes the removal of the deprecated build-windows command in the Makefile. Additionally, there is an update to the documentation that windows is no longer supported for make commands.
Please let me know if there is any additional documentation spots that may be a good candidate to add this change, as this is my first OSS PR!
Fixes the following Github issue: https://github.com/mattermost/mattermost-server/issues/21586
> [GH-21586] - Removed deprecated windows build function in Makefile

- loadtest/control/simulcontroller/actions.go
if length username less than 4 then an error occurs "slice bounds out of range"
Fixed length of string on emulate typing username on searchGroupChannels for simulcontroller
https://github.com/mattermost/mattermost-load-test-ng/issues/525
> fixed emulate typing username on searchGroupChannels for simulcontroller

- config/deployer.sample.json
You get the below error when this isn't added
```bash
ubuntu@ip-172-31-86-142:~/mattermost-load-test-ng$ go run ./cmd/ltctl deployment create
Error: failed to validate config: TerraformStateDir is empty
exit status 1
```
I manually added it to my `deployer.json` and it fixed the error
> Adding `TerraformStateDir` to deployer config

- config/deployer.sample.json
Adding a default value for `S3BucketDumpURI` to the deployer config. This value doesn't appear required, but this should remove confusion when going to set it.
> Add `S3BucketDumpURI` to `deployer.sample.json`

- config/config.sample.json
Reading the docs [here](https://github.com/mattermost/mattermost-load-test-ng/blob/master/docs/loadtest_config.md#serverversion) and noticed the serverVersion setting was not included. This PR just includes it as a blank string, since that appears to be the default.
> Added `ServerVersion` to the usercontroller config

- deployment/terraform/create.go
When attempting to use an existing database and letting the load tester build Mattermost, it will still attempt to configure some search settings. This just adds a check for `HasDB()` before running those commands. Did a quick look to see if any other things would benefit from this and couldn't find any.
> Added HasDB check to default text search config

- loadtest/user/userentity/metrics.go
- loadtest/user/userentity/user.go
- performance/metrics.go
The `loadtest_http_request_time_{sum,count,bucket}` metric is right now a `prometheus.Histogram`, so it doesn't have labels. This PR converts it to a `prometheus.HistogramVec`, and adds three labels to it:
1. Request path
2. Request method
3. Request status code
The observation of the time itself is unchanged, this PR only adds those dimensions.
This is always useful, but in this metric may be even more, since one of the main queries used by the coordinator to decrease users and eventually stop the tests uses this specific metric. Having some more fine-grained information there will help us analyze the results of the load-tests in more detail.
https://mattermost.atlassian.net/browse/MM-49581
> MM-49581: Add path, method and code to HTTPRequestTimes

- deployment/terraform/create.go
PR #535 inverted the order of server creation and admin user creation, so that the deployer was trying to create the user without having set up the server, and hence failed.
As an aside: we should start thinking about setting up some E2E tests; something as simple as "run deployment create and make sure that the server is up" would have prevented this. The thing is: I'm not sure what's the best way to do this without burning money on AWS every time we run CI.
https://mattermost.atlassian.net/browse/MM-49682
> MM-49682: Move admin user creation right after server setup

- docs/faq.md
Added some clarity to the max active users when attempting to loadtest over 52k users.
> Clarified the max active users

- deployment/terraform/create.go
- deployment/terraform/destroy.go
- deployment/terraform/engine.go
This bug is a funny one, since it's not reproducible at all. I've seen it in the wild at some point after bumping to Terraform v1 (much less than before, but this may be just luck), although for me it usually was fixed with a second run of `deployment destroy`. However, it's been reported at least once that this happened even after three executions of `deployment destroy`, which always timed out at the 30-minute mark with only the S3 bucket left to destroy. The only solution that has consistently worked for each and every instance of this bug was to manually empty the S3 bucket, even while the `deployment destroy` command was executing: that is, running `aws --profile mm-loadtest s3 rm s3://bucket.id` concurrently with the destroy.
So that's what this PR does: it adds some defense code to …
> MM-47263: Empty S3 bucket with AWS CLI on destroy

- comparison/loadtest.go
- comparison/loadtest_test.go
#536 introduced a bug that caused the loading of the DB dump to fail when `PermalinkIPsToReplace` is empty, since the resulting `sed` command was malformed. These changes skip the `sed` command altogether when there is nothing to  replace.
https://mattermost.atlassian.net/browse/MM-50046
> MM-40056: Don't use sed if there are no IPs to replace

- docs/faq.md
The docs might be a bit verbose, just tried to give solid examples.
The existing database portion requires a workaround of setting the `InstanceEngine` to `aurora-mysql` to prevent a create command from running - https://github.com/mattermost/mattermost-load-test-ng/blob/2a982ad15971f9166f5c33d1d7263aa57baf7ad8/deployment/terraform/create.go#L387
I'm going to add another related PR to see if I can make that cancel early, same as when it encounters `aurora-mysql` in the string.
https://mattermost.atlassian.net/browse/MM-45947.
> [MM-45947] Added FAQ about using existing infrastructure

- docs/coverage-frequency.md
I'm reviewing the actions frequencies for another ticket and while reading [the guide on this topic](https://github.com/mattermost/mattermost-load-test-ng/blob/master/docs/coverage-frequency.md), I realized it contains screenshots with wrong data that can be confusing: the maximum number of users in Community are 600-700, not 1500-2000. The old screenshots showed graphs that were summing data from multiple instances, not only Community (maybe community-daily, I'm not sure), hence the larger numbers.
--
> Fix screenshots to show real traffic in Community

- Makefile
It's been a while :) 
@coltoneshaw was having [some troubles](https://community.mattermost.com/core/pl/9iheekun8instro73reuafgquw) when building and it turns out we were not using the `golangci-lint` version we are installing but pointing to a system wide one most likely.
> Use locally installed golangci-lint

- loadtest/user/userentity/user.go
Although @agnivade has already fixed this in the latest commit of [this open PR](https://github.com/mattermost/mattermost-load-test-ng/pull/544), I wanted to open this to discuss separately.
There are two alternatives to solve this:
1. What this commit does: use 0 as statusCode when RoundTrip fails. This gives more information to the metric, since 0 is not a valid HTTP status code, which informs that RoundTrip failed. However, if the users don't know this bit, seeing a 0 there in the metric data can be confusing.
2. Observe the metric only if t.transport.RoundTrip(req) finishes successfully. This avoids the confusion with a 0 statusCode, but it also skips all failing round trips, which most probably fail because of a timeout, which are useful to see in the metric.
I think having some …
> MM-50356: Avoid a nil pointer dereference if RoundTrip fails

- Makefile
The `build-windows` rule was removed on #523, but we forgot to remove it from the list of dependencies for `build`. I guess I've been using `make package` and `make test` to test changes, and until now I had not run `make build` :shrug: 
--
> Remove build-windows dependency on build rule

- cmd/ltctl/reset.go
`mattermost db reset` cannot run while an existing
MM instance is running. Therefore we shut it down prior
to running it.
https://mattermost.atlassian.net/browse/MM-48315
> MM-48315: Shutdown MM before running reset

- Makefile
- config/deployer.sample.json
- deployment/config.go
Forgot the `v` :facepalm:
Added a quick check in the Makefile rule so that it doesn't happen again. The error looks like:
```
> NEXT_VER=1.9.0 make prepare-release
The next version, '1.9.0' is not of the form vMAJOR.MINOR.PATCH
make: *** [Makefile:110: prepare-release] Error 1
```
--
> Bump version to v1.8.0

- loadtest/user/userentity/metrics.go
- loadtest/user/userentity/user.go
- performance/metrics.go
v1.8.0 showed a strange behaviour when logging new users in to the instance, as they were added more slowly than in previous versions. See a case of a bad commit (b56daa5):
and compare against the normal behaviour in a good commit (c0a7983).
Both screenshots cover a time window of 20 minutes.
The issue was isolated to the changes in #537, which added more info to the HTTPRequestTimes metric; namely: the path, method and status code of the request. This resulted in:
- A very large set of data for Prometheus to handle (see #550 for a consequence of that), which ended up crashing the metrics server.
- The malfunctioning of the coordinator, which based the logging in and out the users on the metrics, which were broken.
This PR reverts the original PR #537 and the subsequent bug fix #558. With …
> MM-51097: Revert improvement to HTTPRequestTimes metric

- loadtest/control/simulcontroller/controller.go
Now that it's deployed on community we can find the correct frequency.
Calculated by following: https://github.com/mattermost/mattermost-load-test-ng/blob/master/docs/coverage-frequency.md
> Update setPostReminder with accurate frequencies

- loadtest/control/actions.go
- loadtest/control/simulcontroller/actions.go
- loadtest/control/simulcontroller/controller.go
#544 introduced GraphQL, and with it a way to detect whether it was enabled in the server. In order to do this, the agents need to retrieve the client config, but this was not done in the usual flow of the actions, but as soon as `Run()` was called, even before login. This created lots of requests to the config endpoint at the exact same, clogging the server and making the client request times go over the roof. This, in turn, made the coordinator decrease the users, never reaching more than 150-200 users. Something like:
I fixed this by retrieving the client config during the login action, storing it in the user's memstore. This is then used to populate a featureFlags struct---that contains just the GraphQLEnabled flag--- in the simulcontroller, which can be later read by the actions. …
> MM-52110: Avoid requesting the config at the same time for all users

- loadtest/control/gencontroller/actions.go
- loadtest/control/gencontroller/controller.go
The createReply action depended on the currentChannel being set.
Without that, it was throwing an error of channel not found.
So we add a custom switchChannel action to achieve that.
https://mattermost.atlassian.net/browse/MM-52961
> MM-52961: Set CurrentChannel properly in genController

- loadtest/control/gencontroller/actions.go
The problem with using a random channel would be that
there is a probability of the same channel coming up
again and we would unnecessarily make the GetPostsForChannel
call again for the same channel.
This was costly and would waste resources. Instead, we just
get the posts for the channel we just joined. This way
we don't get posts for the same channel again.
> Reduce number of calls to GetPostsForChannel

- loadtest/control/actions.go
- loadtest/control/gencontroller/actions.go
- loadtest/control/gencontroller/controller.go
- loadtest/control/gencontroller/status.go
- loadtest/control/status.go
- loadtest/loadtest.go
There were several instances where we would return early and forget to decrease the counters. PR tries to make it a little less error prone by using named returns in combination with a defer function. Also converting some info logs to warning to help discriminating whether the action was completed or not.
> Improve gencontroller global counters handling

- loadtest/store/memstore/random.go
If a post gets created in a channel which is not loaded
in the store, then RandomPost can crash.
Added a nil check to prevent that.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xebc250]
goroutine 151 [running]:
github.com/mattermost/mattermost-load-test-ng/loadtest/store/memstore.(*MemStore).RandomPost(_, _)
/home/agniva/mattermost/mattermost-load-test-ng/loadtest/store/memstore/random.go:247 +0x530
github.com/mattermost/mattermost-load-test-ng/loadtest/control/gencontroller.(*GenController).createReply(0xc0005301c0, {0x1503378, 0xc0005b8240})
/home/agniva/mattermost/mattermost-load-test-ng/loadtest/control/gencontroller/actions.go:329 +0x5a8 …
```
> Fix crash in memstore

- go.mod
- go.sum
- loadtest/control/gencontroller/actions.go
- loadtest/control/gencontroller/controller.go
- loadtest/control/gencontroller/utils.go
Add a simple `1getPosts` action in the gencontroller that retrieves the first 200 posts of a random channel the user is a member of.
The frequency is set to 100, which is quite low, unless the number of channels or posts configured is even lower. Not sure if we should be too concerned about that, I'm open to discussing it.
https://mattermost.atlassian.net/browse/MM-53154
> MM-53154: Add getPosts action

- cmd/ltctl/main.go
- comparison/deployment.go
- comparison/loadtest.go
- comparison/loadtest_test.go
- config/deployer.sample.json
- deployment/config.go
- deployment/terraform/dump.go
- deployment/utils.go
- docs/deployer_config.md
- loadtest/utils.go
I moved some of the common code under deployment. There's
still slight repetition but it's only at a high level.
I wanted to have some level of freedom in case the workflow
changes between a deployment run and a comparison run. That's
why I refactored only the low-level plumbing.
https://mattermost.atlassian.net/browse/MM-52331
> MM-52331: Automate dump ingestion for normal deployments

- deployment/config.go
- deployment/terraform/info.go
- deployment/terraform/output.go
Sometimes, we just need a server only setup
to test out something. Or we may already have
an agent cluster and just want to deploy a
server side setup.
> Let deployments be made with zero agents

- loadtest/report/output.go
- loadtest/report/output_test.go
Sometimes it can happen that a p99 value for a corresponding avg metric
is not there. We need to handle that case.
https://mattermost.atlassian.net/browse/MM-53644
> MM-53644: Prevent panic when a metric value is not present

- deployment/terraform/strings.go
- loadtest/control/simulcontroller/actions.go
Disabling GraphQL and adding the call to `/users` that the webapp performs on reload. This was used in the base test used to compare frequencies with the cloud customer. See https://community.mattermost.com/private-core/pl/1w83qxzgd7rijbqedmns9fprnc
--
> Basic fixes from the action frequencies analysis

- loadtest/control/simulcontroller/actions.go
- loadtest/control/simulcontroller/controller.go
- loadtest/store/memstore/store.go
- loadtest/store/store.go
Unrelated to the current effort but while working on https://mattermost.atlassian.net/browse/MM-53825 I noticed we were storing FF in the controller which seems a bit odd. I moved that to the `MemStore` and added some basic parsing so that all existing boolean flags should get loaded automatically. Ideally we'd rely on `model.FeatureFlags` but the way flags are returned through the client config makes it hard without resorting to hardcodes  or `reflect` usage.
> Store FF in MemStore

- comparison/loadtest.go
- comparison/loadtest_test.go
- deployment/terraform/dump.go
- deployment/terraform/output.go
- deployment/utils.go
- deployment/utils_test.go
PR partially addresses the issue of permalinks IPs substitution not being properly load balanced. If the target deployment has a proxy we use its IP to do the substitution.
We are left with the case of multiple app servers without a proxy which I am not sure if it's worth investing more time on it. The implementation would be much more complex, likely requiring a bash script or small Go program to make it work since we'd have to pick IPs dynamically when doing the substitution.
I added a warning if we hit this case but happy to hear your thoughts on the above.
https://mattermost.atlassian.net/browse/MM-53348
> [MM-53348] Use proxy instance IP to substitute permalinks IPs

- loadtest/control/actions.go
- loadtest/control/simulcontroller/actions.go
- loadtest/control/simulcontroller/controller.go
- loadtest/control/simulcontroller/utils.go
- loadtest/control/simulcontroller/websocket.go
- loadtest/user/user.go
- loadtest/user/userentity/actions.go
PR reviews some of the use of the `getUsers` call. This is a particularly complex endpoint given that it maps to several client calls depending on the query string passed to it. Some examples:
- `getProfiles`
- `getProfilesInTeam`
- `getProfilesNotInTeam`
- `getProfilesWithoutTeam`
- `getProfilesInChannel`
- `getProfilesInGroupChannels`
- `getProfilesNotInChannel`
- `getProfilesInGroup`
- `getProfilesNotInGroup`
Moreover, there are certain actions that we don't currently have coverage for that would cause additional calls. Some notes I collected so far from this investigation:
- Bumping the reload action frequency will also increase this one so it may get us closer to our target rate "for free".
- Adding users to channels.
- We do a bit of this when creating channels but we don't really …
> [MM-53823] Review getUsers call

- deployment/config.go
- deployment/config_test.go
- docs/config/deployer.md
When using an existing DB cluster via `ClusterIdentifier`, a database is already present, and its name will be different from the one assumed in the code. The first error encountered because of this happened when trying to alter the database to set the default text search config to `english` instead of `simple` (see the ticket), but we can expect more problems of this broken assumption.
To solve this problem, I've added a new `DBName` parameter that the user can set to hardcode the name of the DB:
- If `ClusterIdentifier` is set, it should be the name of the database in such cluster
- If `ClusterIdentifier` is not set, its value can be whatever, and when the new database is created, instead of calling it `${ClusterName}db`, it'll be simply called `${DBName}`. …
> MM-54251: Let the user hardcode the name of the database

- api/agent.go
- deployment/config.go
- deployment/terraform/agent.go
This PR tries to fix the problem of the deployments not using the set of users present in the database dump. Instead of trying to change the user prefix so we can adapt it to the users from the dump, we leverage the already existing `UsersFilePath` setting in `config/config.json`, and expand its usage by:
- Adding a new `UsersFilePath` setting to `config/deployer.json` so that it overrides the data in the deployed agents.
- Splitting the contents of such file into $n$ chunks, where $n$ is the number of agents, and uploading a different chunk to each agent.
- Removing the limitation for mixing user credentials defined in `UsersFilePath` with automatic sign-ups of new users, so that the agent simply switches to automatic sign-ups when there are no more credentials to be consumed from the …
> MM-54315: Expand UsersFilePath usage

- deployment/terraform/create.go
With the new changes, we need a higher timeout
> Bump terraform cmd exec timeout

- comparison/loadtest.go
- deployment/terraform/dump.go
- deployment/utils.go
- deployment/utils_test.go
PR adds an extra step to the db dump loading command that clears existing license related information. This should be the last piece needed to fix the loading issues.
https://mattermost.atlassian.net/browse/MM-54702
> [MM-54702] Automatically clear licenses data from DB dumps

- defaults/json.go
- defaults/json_test.go
- loadtest/user/userentity/helper_test.go
We were trying to set the defaults after parsing. But we were ignoring the errors from the parse. To solve this, we set the defaults first and then override it while unmarshaling the JSON. This achieves the same result but also returns errors correctly.
https://mattermost.atlassian.net/browse/MM-54314
> MM-54314: Return the error correctly from config parse failure

- config/deployer.sample.json
- deployment/config.go
- deployment/terraform/metrics.go
- deployment/terraform/strings.go
- deployment/terraform/strings_test.go
- docs/config/deployer.md
- go.mod
Motivated for the huge amount of memory consumed by profiling 50 agents in the ceiling tests, we decided to allow the user to selectively disable that type of profiling. This PR solves that by making it optional to profile both the app and the agent nodes.
~~Note that the approach to test the generated yaml is a bit esoteric, but parsing the generated yaml seemed even more convoluted than this. I'm open to changing it if your eyes bleed a lot when reading the test, though.~~ Ended up using go-yaml to generate the config, much easier and cleaner.
https://mattermost.atlassian.net/browse/MM-54986
> MM-54986: Disable app and/or agent profiling

- config/deployer.sample.json
- deployment/config.go
Literally what the title says :) I've also updated the base config files we used for the ceiling tests in the launcher instance.
https://mattermost.atlassian.net/browse/MM-55150
> MM-55150: Enable performance insights by default

- docs/release.md
I had somehow understood that RC1 was cut on T-10, but that was wrong: T-10 is code freeze, RC1 is actually cut on T-19.
As the availability of the Mattermost RC1 version was the key date from which the whole timeline was planned, I had to refactor it by:
- Reducing the testing period from 12 days to 5 days.
- Postponing the release to the day *after* RC1 is cut, instead of the day *before*.
I was pretty comfortable with the 12 days we gave to testing (and potential bug fixing), and had considered it maybe too much, since the testing we have planned should be quite short. However, reducing it to 5 days may be too much. This will be informed by the test run of the process we're executing right now, but I want to hear your thoughts (specially @DHaussermann's).
--
> Fix the dates in the release process

- deployment/terraform/create.go
By default, this number was 1000 which didn't allow
typing events to be sent for channels with larger
member counts.
https://mattermost.atlassian.net/browse/MM-55312
> MM-55312: Bump MaxNotificationsPerChannel

- deployment/terraform/create.go
Since we are using ltserver as the site URL, the ws connection
fails when connecting via browser.
https://mattermost.atlassian.net/browse/MM-54455
> MM-54455: Fix CORS issue in load test deployment

- deployment/terraform/create.go
If not disabled, crashes from the tests start
polluting the sentry dashboard
> Disable sentry in load tests

- config/deployer.sample.json
- deployment/config.go
- deployment/config_test.go
Bump version to v1.11.0.
Last time (https://github.com/mattermost/mattermost-load-test-ng/pull/657) we only merged the version bump change to the release branch, `release-1.10`, so we had not updated the sample config files in master to 1.10.0. This is not a showstopper issue, but we need to do it a bit differently. We could simply merge first to `master` and cherry-pick then to `release-x.y`, although there would be a period of time (5 working days?) where the sample config file would have a version that has not been released yet. Not a big problem I guess.
--
> Bump version to v1.11.0-rc1

- cmd/ltctl/main.go
We set the service environment to production
to avoid unexpected license validation failures.
https://mattermost.atlassian.net/browse/MM-54715
> MM-54715: Set service environment automatically

- config/coordinator.sample.json
This PR adds four more queries to the default coordinator metrics. I thought this was going to be straightforward, but the nuances of each of the `node_*` metrics and the complexity of analyzing when a network is congested or not made this a bit more difficult. So a thorough explanation follows, sorry for the long wall of text.
We compute the percentage of CPU used, by subtracting the percentage of time in idle mode (`node_cpu_seconds_total` is already a percentage) to the total:
```
100 - 100 * (avg(irate(node_cpu_seconds_total{instance=~"app.*",mode="idle"}[5m])))
```
This one is clear, already tested in the first version of the ceiling tests, and it does not need much more discussion.
Similarly, we compute the percentage of memory used, by substracting the percentage of available …
> MM-53920: Add new coordinator metrics

- api/agent.go
- loadtest/user/userentity/user.go
We had this issue where a load-test would seem to completely stop after a few minutes when running against a Cloud workspace. Looking at the backtrace I was able to identify that all users were essentially deadlocked waiting for http requests to go through. This seemed strange considering we are definitely [enforcing some timeouts](https://github.com/mattermost/mattermost-load-test-ng/blob/19bc7bc5944b83545b257d0b3693fbe3ded4e9f6/api/agent.go#L340-L351) at both the dialer and transport level. Also I don't believe we ever saw this happening before or we would have addressed it by now. The theory so far is that in this specific case clients don't even get to read response, probably blocking on sending the request.
There's also a good chance this is a regression introduced when updating the …
> [MM-56029] Set HTTP client timeout on UserEntity

- config/deployer.sample.json
- deployment/config.go
- deployment/config_test.go
Bump version to v1.12.0-rc1. Still the same issue [as with v1.11.0-rc1](https://github.com/mattermost/mattermost-load-test-ng/pull/667): versions in master are not updated, and right now stuck at v1.9, because the new release process works on release branches. Created https://mattermost.atlassian.net/browse/MM-56052 to fix it.
--
> Bump version to v1.12.0-rc1

- deployment/terraform/create.go
In the latest data dump, it seems like the migrations take a while to run. It takes more than a minute for the server to be up.
> Bump server ping timeout

- loadtest/control/gencontroller/actions.go
- loadtest/control/simulcontroller/actions.go
The entire Config struct isn't set until the API call is made.
Clients are expected to use the ClientConfig which is guaranteed to be
always set before actions are called. So we use that instead.
https://mattermost.atlassian.net/browse/MM-56288
> MM-56288: Fix panic while getting config

- cmd/ltctl/loadtest.go
- cmd/ltctl/main.go
- deployment/terraform/create.go
- deployment/terraform/db_operations.go
- deployment/terraform/destroy.go
- deployment/terraform/engine.go
- deployment/terraform/info.go
- deployment/terraform/output.go
We add the ability to stop/start the DB cluster after a load-test is complete.
There is a dedicated command that the users can run any time. Additionally, there is also an automated way to stop the DB after a load test finishes, which is exposed via a flag.
Using the flag makes the load test runs synchronously, so it is advised to be used only by advanced users running the command preferably inside an EC2 instance in a screen session.
https://mattermost.atlassian.net/browse/MM-52240
> MM-52240: Stop/Start DB Cluster after load test

- cmd/ltctl/main.go
- deployment/terraform/create.go
When using `config.DBDumpURI`, the generated DB did not get the settings applied from `updatePostgresSettings`, since the latter was executed before ingesting the dump. We cannot simply move the call to `IngestDump` before the call to `Create`, though, because we need the DB cluster up and running to ingest the dump. Thus, this PR moves the call to `IngestDump` inside `Create`, after the DB cluster creation and right before updating the settings.
I'm testing a deployment with these changes as we speak.
https://mattermost.atlassian.net/browse/MM-56918
> MM-56918: Ingest the DB dump from inside Terraform.Create

- config/config.sample.json
- loadtest/config.go
- loadtest/user/userentity/helper_test.go
[The investigation](https://community.mattermost.com/core/pl/kjs9bdxgw7fk7jpuyai1hcpjuh) showed no significant differences in the behaviour of the system between 0%, 0.05% and 2% of users admin, but it did show that our default value here was two orders of magnitude larger than what we see out there.
Will cherry-pick this into `release-1.14` as well.
https://mattermost.atlassian.net/browse/MM-56786
> MM-56786: Adjust PercentOfUsersAreAdmin

- cmd/ltctl/report.go
- docs/compare.md
Just a clarification identified in https://community.mattermost.com/core/pl/adw9x3jb43ngbjcknses4cgrth
--
> Add note about --prometheus-url in local deployments

- loadtest/control/simulcontroller/actions.go
- loadtest/user/user.go
- loadtest/user/userentity/user.go
- loadtest/user/userentity/websocket.go
- loadtest/user/websocket/client.go
We send the message via the websocket whenever
the client state changes.
https://mattermost.atlassian.net/browse/MM-56188
> MM-56188: Add presence indicator to load test

- cmd/ltctl/collect.go
This PR adds an optional step for all files collected during the `collect` command: a `func(input []bytes) ([]bytes, error)` that is called when the corresponding file is downloaded from the instance and before adding it to the collection.
This is used for all app nodes to sanitize the config retrieved from them. As an example, this is an excerpt of the `FileSettings` section in the generated file:
```json
"FileSettings": {
"PublicLinkSalt": "********************************",
"InitialFont": "nunito-bold.ttf",
"AmazonS3AccessKeyId": "AKIA2TV23Z44BXMGHWOE",
"AmazonS3SecretAccessKey": "********************************",
"AmazonS3Bucket": "mm569896989agm.s3bucket",
"AmazonS3PathPrefix": "",
},
```
https://mattermost.atlassian.net/browse/MM-56989
> MM-56989: Sanitize collected MM config

- config/deployer.sample.json
- deployment/config.go
- deployment/config_test.go
Preparing release v1.15.0-RC1
--
> Bump version to v1.15.0-rc1

- deployment/terraform/create.go
- docs/faq.md
These configuration changes are the result of a review of the Mattermost config generated by a load-test. Report: https://mattermost.atlassian.net/wiki/spaces/XYZ/pages/2675015717/Load-test+server+configuration+review
https://mattermost.atlassian.net/browse/MM-55324
> MM-55324: Apply learnings from Mattermost config review

- deployment/terraform/strings.go
Our current model uses a single TCP accept queue and shares
it across all workers. Unfortunately, Linux uses a FIFO model
which will push new connections to the busiest connection
leading to a scenario where some workers will not get
any connection at all.
```
ubuntu@ip-172-27-47-66:~$ sudo netstat -p | grep "3332/nginx" | wc -l
3769
ubuntu@ip-172-27-47-66:~$ sudo netstat -p | grep "3333/nginx" | wc -l
9846
ubuntu@ip-172-27-47-66:~$ sudo netstat -p | grep "3334/nginx" | wc -l
898
ubuntu@ip-172-27-47-66:~$ sudo netstat -p | grep "3331/nginx" | wc -l
59114
ubuntu@ip-172-27-47-66:~$ sudo netstat -p | grep "3335/nginx" | wc -l
98
ubuntu@ip-172-27-47-66:~$ sudo netstat -p | grep "3336/nginx" | wc -l
0
ubuntu@ip-172-27-47-66:~$ sudo netstat -p | grep "3337/nginx" | wc -l
27425 …
```
> Uniformly load-balance connections across cores

- .gitignore
Since the `collect` command drops a *.tar file into the main directory you're running the load tester from, it makes sense to ignore those for the Git repository, so they aren't accidentally committed/sitting in your unstaged changes.
> Add *.tar to the .gitignore

- deployment/terraform/create.go
There was an interesting race condition that could happen during automated comparisons due to `nginx` temporarily flagging the app servers as unavailable. This could result in requests to running app servers to preemptively fail for up to [`fail_timeout`](https://nginx.org/en/docs/http/ngx_http_upstream_module.html#server) seconds (defaults to 10s). 
In the case of the reported issue these requests were made during agent creation which caused the whole comparison to fail even though the app server was already up and running (meaning [this check](https://github.com/mattermost/mattermost-load-test-ng/blob/6dcb79e4c2cc4bbfa9facfe0227d83206ca14583/comparison/loadtest.go#L186) passed successfully).
Setting `max_fails=0` should disable any mechanism to flag dead backends which I think is …
> Prevent nginx from flagging temporarily unavailable backends as dead

- loadtest/control/simulcontroller/websocket.go
- loadtest/user/user.go
- loadtest/user/userentity/user.go
- loadtest/user/userentity/websocket.go
- loadtest/user/websocket/client.go
Adding to the load tester the changes needed to test [this PR](https://github.com/mattermost/mattermost/pull/26604).
Marking as Draft for now since I think we might want to revisit how we want to queue the ACKs to send back.
https://mattermost.atlassian.net/browse/MM-57006
https://mattermost.atlassian.net/browse/MM-57067
> Acknowledge websocket POSTED events when they should be

- comparison/loadtest.go
- deployment/terraform/create.go
- deployment/terraform/dump.go
- deployment/utils.go
- deployment/utils_test.go
The SQL query to clear old licenses data from a DB dump was only executed when using the `DBDumpURI` setting, but not with `ClusterIdentifier`, which is the one we use for larger DB dumps.
I've tested it a couple of times and I didn't get the license error, which I was consistently getting before with the same deployment. Let's see if we can forget about this forever :crossed_fingers: 
https://mattermost.atlassian.net/browse/MM-57915
> MM-57915: Clear licenses data when using ClusterIdentifier

- deployment/terraform/strings.go
In our investigation, we could see more packet drops on the client
side than server side. This would indicate that the TCP buffer
sizes on the client side need some bumping as well.
https://mattermost.atlassian.net/browse/MM-58178
> MM-58178: Apply server side TCP buffer settings to client

- cmd/ltctl/main.go
We check if the DB is available or not before destroying.
Because going ahead with the destroy if the DB is stopped
messes up with the Terraform state.
https://mattermost.atlassian.net/browse/MM-58236
> Check DB status before destroy

- config/deployer.sample.json
- deployment/config.go
- deployment/elasticsearch/elasticsearch.go
- deployment/terraform/create.go
- docs/config/deployer.md
We [recently found out](https://mattermost.atlassian.net/wiki/spaces/XYZ/pages/2827059205/ElasticSearch+load-balancing+investigation+report) that the cause of the unbalanced Elasticsearch queries was the lack of shard replicas in most of the nodes, since we were using the default value of 1 replica per shard, which was allocated to a random data node. The solution to get all data nodes to handle queries at the same rate, then, is to have one replica of the indices' shards in each of them. We only have one shard per index, so this means that every node will contain exactly one copy of each index.
That's what this PR does in [the first commit](https://github.com/mattermost/mattermost-load-test-ng/commit/98b4194c7af8165fa209d5b5a12f0507343c700f): fortunately, the Elasticsearch API allows …
> MM-58347: Ensure all Elasticsearch data nodes have shard replicas

- deployment/config.go
- deployment/config_test.go
We unblock the prefix limitation, and allow
either prefixes.
https://mattermost.atlassian.net/browse/MM-59319
> MM-59319: Allow opensearch installations to be created

- deployment/elasticsearch/elasticsearch.go
I knew I had tested 1-node ES clusters before! I must have tested them prior to the implementation of the MarshalJSON for the RestoreSnapshotOpts struct, though, where I mistakenly assumed the default number of replicas must be 1 instead of 0. This is what made the cluster status to be yellow, and, [contrary to the docs](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/handling-errors.html#handling-errors-yellow-cluster-status) (:shrug:), if we set the number of replicas to 0 when there are no replicas, the cluster status is green, as it should be.
Check an example of a 1-node cluster with a green status :tada: 
https://mattermost.atlassian.net/browse/MM-59312
> Allow 0 shard replicas

- api/agent.go
- deployment/terraform/strings.go
- Turn off the cache_lock. This is unnecessary and
we shouldn't even have done this to start with.
- Set timeout for entire response and not just response header.
It is unclear why exactly this causes the problem. So open to
thoughts and suggestions.
> Improvements from Redis investigation

- api/agent.go
- loadtest/user/userentity/actions.go
- loadtest/user/userentity/user.go
- Allow using `saml` with the external auth provider
- Logic is mostly the same OpenID uses, just added logic to control the redirect from the IDP (keycloak) back to Mattermost to retrieve the cookie, since that uses a form and javascript on the keycloak side.
> feat: allow saml with the external auth provider

- deployment/terraform/strings.go
Release testing for v1.19 of the load-test tool showed that disabling proxy_cache_lock was affecting the performance of the app nodes, which were eventually killed by the overhead of the requests that were no longer waiting for the cache to be updated.
This commit reverts that change, and a subsequent investigation into the proxy_cache_lock_timeout fine-tuning will follow.
See https://mattermost.atlassian.net/browse/MM-59871
--
> Enable proxy_cache_lock again

- deployment/elasticsearch/roundtripper_test.go
There was a race condition where the test ended up creating the SSH client *before* the SSH server was up.
Using `require.Eventually`, we check every 100ms, up to 5s, that the client is correctly created, giving time to the server to start.
https://mattermost.atlassian.net/browse/MM-58444
> MM-58444: Fix race condition in RoundTrip test

- deployment/config.go
- deployment/config_test.go
- deployment/terraform/create.go
- loadtest/control/simulcontroller/config.go
- I had some troubles testing old Mattermost builds (7.10), things kept failing after I put in my custom Mattemost build. Then I saw that if you put in a custom binary it would use the `latest` MM build. So I'm adding flexibility to specify your base build, if you need to.
- Note, this will break previous `deployment.json`s if you were using a `file://` for `MattermostDownloadURL`, but it will give you an error telling you what to do to fix it. Not sure if you really want to avoid that or not.
- Also changed the license check to log the error instead of exit out, since the license file I had to use was not passing the check for whatever reason. I could keep that as a local change, so tell me if you want it removed.
- none
> Allow binaries with specific Mattermost builds; don't fail on license check

- config/deployer.sample.json
The newly added Elasticsearch config settings don't accept string values.
> Fix incorrect deployer.sample.json

- deployment/terraform/create.go
- go.mod
- go.sum
Previously, there was a bug in the logic. Do it properly now.
> Properly use EC2 API to get the proxy details

- go.mod
- go.sum
The newer v7.17 doesn't allow us to test proper Elasticsearch clusters, only Opensearch, so we're downgrading while we find another solution for this so that we can release the new v1.20
--
> Revert go-elasticsearch version bump

- deployment/terraform/create.go
We were incorrectly disabling a config, which
wasn't necessary.
> Remove incorrect DB search config

- cmd/ltctl/comparison.go
- cmd/ltctl/comparison_test.go
This will create a the `results.txt` file and write the results blocks to it eliminating the need to manually copy from the console. 
https://mattermost.atlassian.net/browse/MM-56605
> MM-56605: Create results file and print to file

- loadtest/control/simulcontroller/actions.go
Because there is a return statement which gets executed
if the user isn't part of any teams, this optimization
won't kick in if that's the case.
To let the optimization happen in all cases, we move the
line earlier.
https://mattermost.atlassian.net/browse/MM-60439
> MM-60439: Set websocket scope early

- cmd/ltkeycloak/README.md
- cmd/ltkeycloak/from_mattermost.go
- cmd/ltkeycloak/main.go
- deployment/terraform/create.go
Added a `--migrate-all-users` flag that forces migration of all users, which changes two things:
- Skips checking if the `authmethod` for the Mattermost user is `password`
- When creating a Keycloak user, instead of directly failing if the user exists, when the flag is set we will try to retrieve that user and update the Mattermost user accordingly.
- Changed the `UpdateUser` to `UpdateUserAuth` to work with newer Mattermost versions.
This flag is required for environment where the data loaded into Mattermost already points users to an external auth provider. Even if the data was wrong and wasn't working, the tool couldn't migrate those users as it was.
> feat(ltkeycloak): added flag to force migrate all users

- cmd/ltctl/main.go
This has caused more headache than benefit. The problem is that
if you mess up your deployment slightly and lose your cluster,
then you cannot clean up any other resources because it fails
on "DB cluster not found".
Currently, this causes problems while destroying deployments
with db parameter groups. While that's a separate bug, Stu
also ran into this problem when he messed up his setup.
Whereas, if this check didn't exist, it would naturally fail
during terraform destroy. This check just made it fail sooner.
> Remove checking DB status while destroying

- deployment/terraform/strings.go
It seems that https://github.com/mattermost/mattermost-load-test-ng/pull/807 stole the `static_configs:` line from the cloudwatch section and gave it to the `netpeek` one :smiling_imp:
--
> Fix malformed Prometheus configuration YAML file

- config/deployer.sample.json
- config/deployer.sample.toml
- deployment/config.go
- deployment/config_test.go
Defaulting on `us-east-1c` since it was proven to work, while others may have issues (especially 1a and 1b).
Still undecided on whether we should force the default if unset (empty). Let me know if you have any thoughts.
> Use `us-east-1c` as default AZ

- cmd/ltctl/collect.go
Instead of relying on the existence of app nodes, which may not be available in an agents-only deployment, to verify that a deployment is ready, directly get the list of all available clients and then check if we have at least one to collect data from. Otherwise, stop the log collection.
https://mattermost.atlassian.net/browse/MM-49059
> MM-49059: Fix collect error when no apps are deployed

- cmd/ltctl/comparison.go
- comparison/comparison.go
- comparison/loadtest.go
- comparison/output.go
Before this PR, when running a comparison, the tool would cancel all tests if any single one of them would fail. This does not need to be like this, since all runs in a comparison are independent of each other: they're completely different deployments. If one of them fails, we can still try to finish the other ones, so that we only need to retry one of them in a second try.
This PR does exactly that: it makes the independent deployments actually independent by removing the cancel channel, which was used to broadcast the cancel to all deployments in the case of a single failure. Removing this makes the code slightly less complex as well.
And while I was here:
- I've removed an ancient TODO that was fixed four years ago (:shrug:)
- I've added the deployment ID to error log lines to know …
> MM-52099: Be more gentle with comparison failures

- defaults/validate.go
- defaults/validate_test.go
- deployment/config.go
- deployment/terraform/create.go
If we are not deploying app nodes (to load-test an already existing Mattermost installation), we don't need to validate the license (first commit). Actually, we don't even need to specify a file in the config at all (second commit).
https://mattermost.atlassian.net/browse/MM-56823
> MM-56823: Validate license only when deploying app nodes

- .github/workflows/ci.yml
- go.mod
Bump the Go version to 1.22, using the latest minor version for the toolchain.
https://mattermost.atlassian.net/browse/MM-61011
> Bump Go version to 1.22

- deployment/terraform/create.go
It turns out that this import has been silently failing forever. Starting with Terraform v1.9, though, it started triggering an error that made the deployment fail: `Configuration for import target does not exist`. For more information, see https://developer.hashicorp.com/terraform/language/upgrade-guides#invalid-import-blocks
But the thing is that we don't actually need it! We already create the RDS cluster conditionally, skipping it if `ClusterIdentifier` is specified. Also, the DB instances are attached to the new cluster if one is created but, again, if `ClusterIdentifier` is specified, they are attached to that one.
That's why the whole thing has always worked despite the import command failing: we don't actually need it.
https://mattermost.atlassian.net/browse/MM-60501
> MM-60501: Remove import of the restored RDS cluster

- config/deployer.sample.json
- deployment/config.go
- deployment/opensearch/opensearch.go
- deployment/terraform/create.go
While restoring, we check for the total size of the indices
and throw an error if the total size exceeds the configured disk space.
Ideally, we should have thrown an error pre-deployment. But from what
I could see, there is no way to actually find out the size of the index
before restoring the snapshot.
Let me know if you think there's a better way.
```
info  [2024-10-14 17:40:13.563 +05:30] Vacuuming the tables                          caller="terraform/create.go:917" cmd="psql 'postgres://mmuser:mostest80098bigpass_@agnivalocallt-db-0.c0gzspkyf2r5.us-east-1.rds.amazonaws.com/agnivalocalltdb?sslmode=disable' -c 'vacuum analyze channels, sidebarchannels, sidebarcategories, posts, threads, threadmemberships, channelmembers;'"
info  [2024-10-14 17:40:34.297 +05:30] Restoring ElasticSearch …
```
> MM-60393: Show error when disk space is less than ES index size

- cmd/ltagent/init.go
- cmd/ltctl/reset.go
- comparison/loadtest.go
- deployment/terraform/agent.go
The high concurrency of the init process could cause some permission errors [when fetching channels for a previously joined team](https://github.com/mattermost/mattermost-load-test-ng/blob/0d94529ac36a34ce004c5561b086d71354438f98/loadtest/control/gencontroller/actions.go#L499-L501). Since we try to fetch the channels right after joining a team, this could naturally happen as a result of replica lag. 
However, certain app nodes could consistently return 403 as somehow the `model.Session.TeamMembers` would be not in sync with the real state (user joined all teams). I couldn't fully understand why that is happening, so it remains something to potentially investigate separately.
The fix on this side is pretty naive: we merely force the init to happen on the first app server, preventing any of …
> [MM-60412] Fix potentially stuck init process

- deployment/terraform/strings.go
- deployment/terraform/strings_test.go
- loadtest/user/userentity/user.go
- loadtest/user/userentity/utils_test.go
The issue causing the mismatch in 403 errors was due to the extremely high cardinality of the `path` label used in the `loadtest_http_errors_total` counter vector. The errors were tracked correctly by the client, but the `increase` query would return an empty set. 
To address this, we replace the IDs in the request path to keep the cardinality low. 
If we need that information, we can always find it in the proxy access logs. Speaking of which, I reviewed what we were logging to include more useful info and using JSON for easier filtering/parsing in Loki.
https://mattermost.atlassian.net/browse/MM-60297
> [MM-60297] Fix `loadtest_http_errors_total` metric

- deployment/terraform/engine.go
We were incorrectly using the Pipe functions
and logging it by parsing each newline. Simply
setting the Stdout/StdErr fields is the correct way
and avoids detecting newlines.
This also improves logging by not splitting every
single newline into a separate log line. Rather
logging a whole string from Terraform in one shot.
Fixes https://github.com/mattermost/mattermost-load-test-ng/issues/835
> Properly set the Stdout/StdErr field for commands

- docs/config/deployer.md
This improves the documentation on `MattermostDownloadURL`, whose use cases were modified after https://github.com/mattermost/mattermost-load-test-ng/pull/767. The comment in the code was updated, but not the user-facing docs.
Thanks @harshilsharma63 for flagging this on https://community.mattermost.com/core/pl/85f7rnesdb8edfnnz7y7s6bpce <3
--
> Update docs on MattermostDownloadURL

- config/deployer.sample.json
- deployment/config.go
- deployment/config_test.go
Bump version to v1.22.0
Also [pinged the Delivery team](https://hub.mattermost.com/private-core/pl/cthiew6w57nk9cbiboy48taw1a) to reopen https://mattermost.atlassian.net/browse/CLD-7570, so we can forget about these PRs.
--
> Bump version to v1.22.0

- config/comparison.sample.toml
- config/coordinator.sample.toml
- docs/readme.md
- examples/config/README.md
- examples/config/perfcomp/comparison.toml
- examples/config/perfcomp/config.toml
- examples/config/perfcomp/coordinator.toml
- examples/config/perfcomp/deployer.toml
- examples/config/release/comparison.toml
- examples/config/release/config.toml
- examples/config/release/coordinator.toml
- examples/config/release/deployer.toml
This is something I've been wanting to do for a long while: having a set of config files that can be used as starter packs for other workflows. We already use two sets internally, which are the ones that I've uploaded here: the config files for release testing of the tool itself, and the config files for the performance comparisons of Mattermost new releases.
Some questions you may have:
- Why now? Because we've spent soooo much time these days trying to merge old config files with new fields for the latest release testing.
- And why TOML and not JSON? Because I want to start using it. The possibility of having comments in the files is incredibly useful, and just that outweighs other minor annoyances (e.g. TOML arrays, which are a bit weird). In any case, it's an experiment. If it doesn't …
> MM-61311: Version-controlled config samples

- cmd/ltctl/report.go
- deployment/config.go
- deployment/config_test.go
The problem is that when running local tests, the report generator errors out with a misleading message instead of explicitly stating that there is no deployment and therefore cannot generate a report. The error message should be clearer.
This pull request changes the error message when there is no ongoing deployment while generating a report. It improves error handling by checking whether the current Terraform state includes the metrics instance and errors out when it doesn't. To implement this, the `ExternalDBSettings.DriverName` configuration was changed to use PostgreSQL by default.
--> https://mattermost.atlassian.net/browse/MM-56949
Github issue: https://github.com/mattermost/mattermost/issues/29148
> Misleading error when generating a report with no deployment

- deployment/terraform/create.go
Cherry-pick #849 to `release-1.23`. Even though I have not released the RC-1 version yet, the branch is protected and I cannot force-push to it (I should have cut it *after* #849 was merged, but alas). Anyway, we need to cherry-pick that now.
--
> Cherry-pick of #849: Use os.MkdirAll, which is thread-safe

- deployment/terraform/agent.go
- deployment/terraform/create.go
We need to restart the service so that it picks up the updated environment file with the enabled collector.
https://mattermost.atlassian.net/browse/MM-59994
> [MM-59994] Fix `ethtool` metrics

- cmd/ltctl/main.go
- comparison/comparison.go
- comparison/loadtest.go
- deployment/terraform/create.go
Last week, @streamer45 realized that we're not running the `vacuum` step in comparison runs. Actually, we do run it, but we do it *before* loading the database dump, which is of course completely useless.
This PR refactors that step (and the rest of post-processing we do after the DB is ready: clear licenses data and run extra SQL commands) out from `Terraform.Create`, so we can call it when needed in both usages of that function: in the usual `deployment create` command and in the `comparison run` command.
There's still a lot of work to decouple everything going on in `Terraform.Create`, but this is a baby step in that direction.
https://mattermost.atlassian.net/browse/MM-61944
> MM-61944: Decouple vacuum step from Terraform.Create and use it in Comparison

- comparison/comparison.go
- comparison/config.go
- comparison/config_test.go
- comparison/deployment.go
- comparison/loadtest.go
This PR makes sure that we use a unique filename for each build file we need in comparisons by:
1. Using a new `getBuildFilename` function to get the filename of each build given the configuration. The function adds the config's label to the filename.
2. Ensuring the labels for both the base and new builds are different.
https://mattermost.atlassian.net/browse/MM-62026
> MM-62026: Fix comparison build filenames

- deployment/terraform/destroy.go
When destroying a cluster that deploys an S3 bucket, we try to speed up its deletion by calling `aws s3 rm s3://my-bucket` concurrently while we run `terraform destroy`. This was added to fix https://mattermost.atlassian.net/browse/MM-47263, since we were seeing too many timeouts due to the S3 bucket not being properly destroyed in time. Emptying the bucket while other resources are being destroyed has worked to fix the timeout issue, but it introduces a new error: if the bucket is destroyed by Terraform before the `aws s3 rm` command finishes, this command, and thus the whole `{comparison,deployment} destroy` command, fails.
This is a spurious failure: all resources, including the S3 bucket, have been destroyed (that's exactly why the `aws s3 rm` command fails, actually), so we can …
> MM-62075: Ignore error from aws s3 rm command

- coordinator/performance/monitor.go
Replaces the datetime calculation with a Ticker in the monitor's main loop
Applies to https://mattermost.atlassian.net/browse/MM-61922
> fix: use a ticker in the monitor loop

- deployment/config.go
- deployment/terraform/keycloak.go
Use a naive approach to password escaping for keycloak if the tilde character is included in the password.
An improvement for this would be to limit the characters in the field validation.
https://mattermost.atlassian.net/browse/MM-61278
> fix: escape keycloak password to improve shell compat

- deployment/terraform/dump.go
- deployment/terraform/ssh/ssh.go
After I started testing using a huge number of users in the same team/channel combination I experienced slowness on some of the tasks that stop/start the mattermost servers to run jobs. Those commands were being executed in serial, so I changed the function so the commands run in parallel.
> feat: execute commands async to speed up tasks

- Makefile
This allows to use that path in the deployer configuration file while making changes to the load test without the need to update the field each time you create a new package.
https://mattermost.atlassian.net/browse/MM-61294
> chore: create latest.tar.gz when packaging

- cmd/ltkeycloak/from_mattermost.go
Removed the `errorsChan` channel in the `ltkeycloak` command. The errors were being sent **and logged**, but the channel was never consumed, getting the command stuck if some errors appeared. In the feature branch we just increased the channel size to the number of users being imported but it's better to just remove it and allow regular logging to work this out.
https://mattermost.atlassian.net/browse/MM-61914
> [MM-61914] remove usage of unused errorsChan in ltkeycloak command

- deployment/terraform/utils.go
We have the AWS Region parameter but that can conflict with the default values or the profile values (specifically if region is not set there).
This pull request adds the region option when creating the AWS Client to match the one in the configuration.
https://mattermost.atlassian.net/browse/MM-61279
> chore: get aws client with region set up in config

- cmd/ltctl/main.go
- deployment/config.go
- docs/config/deployer.md
Avoid running the database initialization commands if providing an external database since the `IngestDump` only works for terraform created databases. External databases are usually already populated and ready to use as they come from backups.
https://mattermost.atlassian.net/browse/MM-61280
> [MM-61280] disable init data if providing external database

- deployment/terraform/metrics.go
Downloads the latest Dashboard v2 revision from the Grafana gallery and installs it into the environment automatically. It naively removes the DS_PROMETHEUS variable from the JSON dashboard code so it automatically uses the primary prometheus source present in the deployment.
https://mattermost.atlassian.net/browse/MM-61912
> [MM-61912] Download and install latest Dashboard v2 automatically

- api/agent.go
- loadtest/user/userentity/actions.go
Refactors the way the users log in to use login by email instead of by username. The problem with this was that when providing a txt file with a list of email/passwords the login flow used the username extracted from the email and that may not be accurate for non-synthetic dumps.
This pull request changes the login flow to use `GetLoginByEmail` instead of `GetLoginByUsername` but still returns the internal `user` object with the extracted username from the email.
https://mattermost.atlassian.net/browse/MM-61910
> [MM-61910] refactor: log users by email

- deployment/terraform/metrics.go
- deployment/terraform/strings.go
Use the region in the deployer configuration inside the YACE template, instead of forcing it to `us-east-1`.
https://mattermost.atlassian.net/browse/MM-61911
> [MM-61911] yace: use deployer config region

- deployment/terraform/strings.go
- deployment/terraform/strings_test.go
The debug exporter logs whatever payload the collector sends to Loki to the syslog, so it's easier to... well, debug the collector itself :) This was really useful when setting the whole logging system up, but it's no longer needed, and if there's any unrelated error (like an agent being down), `/var/log/syslog` can quickly end up consuming the whole disk (which is what motivated this change). The logs will still be sent to Loki if there's such an error, so it's not like we're removing useful info for debugging potential issues.
--
> Remove OpenTelemetry collector's debug exporter

- deployment/terraform/db_operations.go
In case of ExternalDB there will be no cluster identifier
from a Terraform deployment.
> Check for ExternalDBSettings while starting a load test

- Makefile
- config/deployer.sample.json
- config/deployer.sample.toml
- deployment/config.go
- deployment/config_test.go
- examples/config/ci/deployer.json
Now that https://mattermost.atlassian.net/browse/CLD-7570 is resolved, we have https://latest.mattermost.com/mattermost-load-test-ng-linux, which will always point to the latest release of the tool. This PR removes the hardcoded versions in the URLs in favour of this new URL, and removes the Makefile rule `prepare-release`, which is no longer needed.
https://mattermost.atlassian.net/browse/MM-63351
> MM-63351: Use latest URL

- examples/config/ci/deployer.json
Fixing what I broke with #895: the config files for CI should not have been updated. Will cherry-pick this to `release-1.24` as soon as it's merged to release a new v1.24.2 :man_facepalming: 
--
> Use v1.24.1 for the CI pipeline, not latest

- .goreleaser.yml
When there is more than one tag in a commit, git sorts them lexicographically by default, so v1.26.0-rc1 is listed *after* v1.26.0. As goreleaser picks the latest one listed by git, we need to change the sorting method, so that v1.26.0 is listed after v1.26.0-rc1. We do this by setting `tag_sort` to -`version:creatordate`, so that they are sorted by creation date. As the stable tag will always be created after the release candidate tag, this will work as expected.
More info in the docs: https://goreleaser.com/customization/git/
This had never been a problem until now because we always had at least one commit between the RC tag and the stable tag: the commit changing the latest URL strings. As we don't need that anymore (yay!), we've encountered this issue for the first time now. I'll need …
> goreleaser: Use -version:creatordate to pick latest tag

- loadtest/store/memstore/random.go
Just an oversight in the error returned, which should use the common `ErrScheduledPostStoreEmpty`.
https://mattermost.atlassian.net/browse/MM-63536
> MM-63536: Use ErrScheduledPostStoreEmpty for empty store err

- go.mod
- go.sum
- loadtest/control/simulcontroller/actions.go
- loadtest/control/simulcontroller/utils.go
- loadtest/store/memstore/random.go
- loadtest/store/memstore/random_test.go
- loadtest/store/memstore/store.go
- loadtest/store/memstore/store_test.go
- loadtest/store/store.go
- loadtest/user/user.go
- loadtest/user/userentity/actions.go
- loadtest/user/userentity/utils.go
- loadtest/utils_test.go
Our existing viewThread implementation was incorrect. It used
to load pages of posts in a thread as a user scrolls up or down.
That is the ideal way, but our webapp actually loads the entire
thread. That is the first change done here.
Then, we apply the performance optimization where for subsequent
loads of a thread, we use the lastUpdateAt of a thread and pass
that to the API call.
https://mattermost.atlassian.net/browse/MM-63542
> MM-63542: Add load-test coverage for new RHS loading pattern

- api/agent.go
- api/agent_client_test.go
- loadtest/control/actions.go
- loadtest/control/simulcontroller/actions.go
- loadtest/control/simulcontroller/controller.go
- loadtest/store/memstore/store.go
- loadtest/store/store.go
- loadtest/user/user.go
- loadtest/user/userentity/actions.go
This PR does a few things now, after Agniva's comments:
- It adds a new function to get *all* the channel memberships of *all* teams using the `/users/$user_id/channel_members` endpoint, named `GetAllChannelMembersForUser`. This is now called from `control.Reload`, right after `GetChannelsForUser`, mimicking [the behaviour in the webapp](https://github.com/mattermost/mattermost/blob/6ae0efd285bfd925e28ce86933c2a4b2170cc093/webapp/channels/src/components/team_controller/team_controller.tsx#L60-L66).
- It removes the calls to `GetChannelsForTeamForUser` both from `control.Login` and from `simulcontroller.loadTeam`. We can do this because we were already calling `GetChannelsForUser` in `control.Reload`: this call retrieves *all* channels from *all* teams.
- It removes the call to …
> MM-63724: Remove excessive calls to GetChannelsForTeam

- loadtest/user/userentity/report.go
- loadtest/user/userentity/user.go
There were various bugs in the implmentation logic.
1. Start and End are ms, not s.
2. The Version field is compulsory to be set in the
report struct.
3. The timestamp field is unused entirely in the server.
So we remove it here and will remove from server
as well.
https://mattermost.atlassian.net/browse/MM-62365
> MM-62365: Fix errors in submitPerformanceReport

- deployment/terraform/create.go
- deployment/terraform/generated_values.go
- deployment/terraform/generated_values_test.go
- deployment/terraform/info.go
- deployment/terraform/metrics.go
- deployment/terraform/utils.go
- docs/faq.md
- docs/load-test-how-to-use.md
Second part of https://mattermost.atlassian.net/browse/MM-63827, in addition to #909. This PR generates a random password for Grafana's `admin` user.
The less pretty part is that we need to store the password locally to persist it between calls to `ltctl` commands, so that we can show it on `deployment info`. As this flow is only needed when deploying to Terraform, I've created a new `GeneratedValues` struct that stores values generated during deployment that are not user-specified (only this Grafana admin pass for now). I added a field of that type to the `Terraform` struct, and then I persist that struct to disk in a new file inside `TerraformStateDir`, which is already a directory that `ltctl` controls and that stores Terraform-related state.
I first though about implementing a full …
> MM-63827: Generate random password for Grafana admin user

- Makefile
- config/deployer.sample.json
- scripts/json_validator.go
Looks like `deployer.sample.json` wasn't valid JSON (due to an extra comma). I added a script to run as part of `check-style` to avoid merging invalid JSON files in the future.
> Fix validation of sample JSON files

- deployment/terraform/create.go
- deployment/terraform/generated_values.go
- deployment/terraform/generated_values_test.go
In #911, we added logic to persist the dynamically generated Grafana password. We do this by storing it locally in the `TerraformStateDir/generated_values.json` file. This works great for single deployments, but when using the `comparison` command, `TerraformStateDir` is shared among all deployments in the comparison. As the filename is hardcoded, only dependant on `TerraformStateDir`, the deployments in a comparison will inevitably override each other's data, so that the `generated_values.json` file ends up containing only the data of the last deployment that edited it. This, in turn, triggers an error when generating the results of the comparison, since dashboards cannot be uploaded without the admin password.
In order to fix this, we prefix the filename with the deployment ID, which is …
> [AI assisted for tests] MM-64392: Fix grafana pass generation in comparisons

- loadtest/control/simulcontroller/actions.go
`GetTeamScheduledPosts` can only work for v10.3.0 and later. Found during an unplanned comparison between 9.11 and 10.5 :nerd_face: 
--
> Avoid calling GetTeamScheduledPosts in old versions

- loadtest/user/userentity/actions.go
The new streaming logic for `model.Client4.GetChannelMembersWithTeamData` makes `UserEntity.GetAllChannelMembersForUser` to fail with the error 
```
control.Reload github.com/mattermost/mattermost-load-test-ng/loadtest/control/actions.go:834 No channel member found for that user ID and channel ID.
```
The cause is still unknown, but I've decided to remove it for three main reasons:
1. We need a quick fix in place to unblock the performance comparison of v10.10
2. We were not really *streaming* anything per se, but receiving everything in one go. This code path was added to match the new client, but the difference in performance should be negligible.
3. The new logic had been already released in v10.9, the latest stable release, so it should not a bug in the server, but in our tooling. …
> MM-64729: Remove new logic for GetChannelMembersWithTeamData

- comparison/comparison.go
- comparison/deployment.go
- comparison/output.go
The solution I came up with to the credentials issue that causes https://mattermost.atlassian.net/browse/MM-63312 is to have a goroutine refreshing the credentials in the background. Although that is a CI-specifc problem, I needed to tweak a couple of things in the base logic of the comparisons. That is what this PR is about.
The obstacle for that solution was that we were kind of misusing the `deploymentAction` function. That function creates a Terraform instance per deployment and calls the function provided by the caller in each deployment concurrently. However, we were repeating that logic for running the same action in each deployment three times. Simplifying, the code looked like this:
```go
// 1. Create the deployments
c.deploymentAction(func(t *terraform.Terraform, dpConfig …
```
> MM-63312: Use a single Terraform instance per deployment in comparisons

- deployment/terraform/agent.go
Probably caused by #919 
The prometheus setup was locked behind a RHEL check, which I think shouldn't be the case.
> fix: prometheus exporter setup behind rhel for agents

- deployment/terraform/assets/variables.tf
Aurora Postgres v14.9 EOL was last month! From [the support schedule](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraPostgreSQLReleaseNotes/aurorapostgresql-release-calendar.html#aurorapostgresql.minor.versions.supported):
I realized this when trying to stop the DB for the weekend in a deployment I have around and I got this warning:
```
info  [2025-10-03 15:22:27.197 Z] An error occurred (InvalidDBClusterStateFault) when calling the StopDBCluster operation: This DB cluster uses an engine version that has reached its end of life. Upgrade your DB cluster to version 14.15 or higher before stopping. caller="deployment/utils.go:119"
```
--
> Use latest minor version for Postgres v14
