example/samplecontroller/controller.go, loadtest/control/controller.go, loadtest/control/simplecontroller/controller.go, loadtest/control/simplecontroller/controller_test.go
PR implements UserController.SetRate() method.
https://mattermost.atlassian.net/browse/MM-20302
=> [MM-20302] Implement UserController.SetRate()

example/samplestore/store.go, example/sampleuser/user.go, go.mod, go.sum, loadtest/control/simplecontroller/actions.go, loadtest/control/simplecontroller/controller.go, loadtest/store/memstore/store.go, loadtest/store/memstore/store_test.go, loadtest/store/store.go, loadtest/user/user.go, loadtest/user/userentity/actions.go
Added CreatePost, cleaned up some loose ends (proper error returning)
@streamer45  Please let me know if this is what you had in mind, if so I'll continue with the rest of the tickets
=> MM-20709 - Add CreatePost

example/sampleuser/user.go, loadtest/user/user.go, loadtest/user/userentity/actions.go
Related issue https://mattermost.atlassian.net/browse/MM-20711
=> Added User.CreateDirectChannel

example/sampleuser/user.go, loadtest/user/user.go, loadtest/user/userentity/actions.go
Related issue https://mattermost.atlassian.net/browse/MM-20710
=> Added User.CreateChannel

example/sampleuser/user.go, loadtest/user/user.go, loadtest/user/userentity/actions.go
Implements `userentity.CreateUser()`.
The function is a simple wrapper to the underlying API call. It will be mainly used during initial data generation by a sysadmin.
https://mattermost.atlassian.net/browse/MM-20880
=> [MM-20880] Implement userentity.CreateUser()

example/sampleuser/user.go, loadtest/user/user.go, loadtest/user/userentity/actions.go
Added the method User.GetUsersStatusesByIds for the user entity
https://mattermost.atlassian.net/browse/MM-20844
=> Added User.GetUsersStatusesByIds

example/samplestore/store.go, example/sampleuser/user.go, loadtest/store/memstore/store.go, loadtest/store/memstore/store_test.go, loadtest/store/store.go, loadtest/user/user.go, loadtest/user/userentity/actions.go
**Summary**
PR implements userentity.RemoveUserFromChannel.
It also adds new tests for the remove channel members in the storage
**Ticket**
https://mattermost.atlassian.net/browse/MM-20845
=> Add User.RemoveUserFromChannel

example/sampleuser/user.go, loadtest/user/user.go, loadtest/user/userentity/actions.go
**Summary**
This PR implements the userentity.AddChannelMember method
**Ticket**
https://mattermost.atlassian.net/browse/MM-20846
=> Added user.AddChannelMember

example/sampleuser/user.go, loadtest/user/user.go, loadtest/user/userentity/actions.go
**Summary**
This PR adds support for the userentity.GetChannel method
**Ticket**
https://mattermost.atlassian.net/browse/MM-20847
=> Added user.GetChannel method

example/sampleuser/user.go, loadtest/user/user.go, loadtest/user/userentity/actions.go
PR implements `UserEntity.UpdateUser()`
https://mattermost.atlassian.net/browse/MM-21029
=> [MM-21029] Implement userentity.UpdateUser()

example/sampleuser/user.go, loadtest/user/user.go, loadtest/user/userentity/actions.go
PR implements `UserEntity.UploadFile()`
https://mattermost.atlassian.net/browse/MM-21021
=> [MM-21021] Implement UserEntity.UploadFile()

example/sampleuser/user.go, loadtest/user/user.go, loadtest/user/userentity/actions.go
PR implements `UserEntity.PatchUser()`
https://mattermost.atlassian.net/browse/MM-21030
=> [MM-21030] Implement userentity.PatchUser()

example/samplestore/store.go, example/sampleuser/user.go, loadtest/store/memstore/store.go, loadtest/store/memstore/store_test.go, loadtest/store/store.go, loadtest/user/user.go, loadtest/user/userentity/actions.go
PR implements `userentity.AddTeamMember()` and related store methods.
https://mattermost.atlassian.net/browse/MM-20858
=> [MM-20858] Implement userentity.AddTeamMember()

example/samplestore/store.go, example/sampleuser/user.go, loadtest/store/memstore/store.go, loadtest/store/memstore/store_test.go, loadtest/store/store.go, loadtest/user/user.go, loadtest/user/userentity/actions.go
**Summary**
This PR adds User.SaveReaction method and the reaction storage methods as well
**Ticket**
https://mattermost.atlassian.net/browse/MM-20849
=> Add User.SaveReaction

.circleci/config.yml
Simple CI workflow that runs the linter and tests for all branches. This is an initial approach and it doesn't contemplate packaging nor releases
https://mattermost.atlassian.net/browse/MM-21110
=> Replace old CI config with a lint&test workflow

example/samplestore/store.go, example/sampleuser/user.go, loadtest/store/memstore/store.go, loadtest/store/memstore/store_test.go, loadtest/store/store.go, loadtest/user/user.go, loadtest/user/userentity/actions.go
**Summary**
This PR implements the GetPostsForChannel method and also adds the storage methods to dump a slice of posts in the storage
**Ticket**
https://mattermost.atlassian.net/browse/MM-20850
=> Implements User.GetPostsForChannel

example/sampleuser/user.go, loadtest/user/user.go, loadtest/user/userentity/actions.go
**Summary**
This PRs adds a new method `GetReactions` to the user entity
**Ticket**
https://mattermost.atlassian.net/browse/MM-20852
=> Adds User.GetReactions method

example/samplestore/store.go, example/sampleuser/user.go, loadtest/store/memstore/store.go, loadtest/store/store.go, loadtest/user/user.go, loadtest/user/userentity/actions.go
added RemoveTeamMember
https://mattermost.atlassian.net/browse/MM-20860
=> added RemoveTeamMember

example/samplecontroller/controller.go, loadtest/control/simplecontroller/controller.go
Using an empty struct is more idiomatic and also better
because it does not take up any space.
=> Use empty struct in the stop chan signal

.gitignore, example/sampleuser/user.go, loadtest/user/user.go, loadtest/user/userentity/actions.go, loadtest/user/userentity/utils.go
This PRs adds the method `GetPostsBefore` to the user entity
https://mattermost.atlassian.net/browse/MM-21026
=> Implements User.GetPostsBefore

example/sampleuser/user.go, loadtest/user/user.go, loadtest/user/userentity/actions.go
This PR adds GetPostsAfter method to the user entity
https://mattermost.atlassian.net/browse/MM-21027
=> Adds User.GetPostsAfter to the user entity

example/sampleuser/user.go, loadtest/user/user.go, loadtest/user/userentity/actions.go
This PR adds the `GetProfileImage` method to the user entity
https://mattermost.atlassian.net/browse/MM-21132
=> Adds GetProfileImage to user entity

example/sampleuser/user.go, loadtest/user/user.go, loadtest/user/userentity/actions.go
This PR adds GetEmojiImage to the user entity
https://mattermost.atlassian.net/browse/MM-21135
=> Adds GetEmojiImage to the user entity

example/samplecontroller/controller.go, loadtest/control/simplecontroller/actions.go
Failing to satisfy the password restrictions result in an error message:
Your password must contain at least 10 characters made up of at least one lowercase letter,
at least one uppercase letter, at least one number, and at least one symbol (e.g. "~!@#$%^&*()").
=> Satisfy password restrictions

example/samplestore/store.go, example/sampleuser/user.go, loadtest/store/memstore/store.go, loadtest/store/memstore/store_test.go, loadtest/store/store.go, loadtest/user/user.go, loadtest/user/userentity/actions.go
This PRs adds:
- User.GetChannelsForTeam method to the user entity
- SetChannels method for the storage
https://mattermost.atlassian.net/browse/MM-21131
=> Implements User.GetChannelsForTeam

example/sampleuser/user.go, loadtest/control/simplecontroller/controller_test.go, loadtest/user/user.go, loadtest/user/userentity/actions.go
Implement User.GetChannelsForTeamForUser
https://mattermost.atlassian.net/browse/MM-21231
=> MM-21231: Implement User.GetChannelsForTeamForUser

example/sampleuser/user.go, loadtest/user/user.go, loadtest/user/userentity/actions.go
This PR adds GetFilePreview to the user entity
https://mattermost.atlassian.net/browse/MM-21137
=> Implements GetFilePreview in the user entity

example/sampleuser/user.go, loadtest/user/user.go, loadtest/user/userentity/actions.go
Implement User.GetTeamMembersForUser
https://mattermost.atlassian.net/browse/MM-21234
=> MM-21234: implement User.GetTeamMembersForUser

example/samplestore/store.go, loadtest/control/simplecontroller/actions.go, loadtest/control/simplecontroller/controller.go, loadtest/store/memstore/store.go, loadtest/store/memstore/store_test.go, loadtest/store/store.go
Added all the methods that we currently have that happens
when a user performs a reload.
Marked the rest of them as TODO.
While at it, we also move the getter methods from MutableUserStore
to UserStore to be able to access from the controller.
Tested with this piece of code. (Needs the server running)
```go
func TestReload(t *testing.T) {
}))
t.Logf("%+v", status)
t.Logf("%+v", status)
status = c.reload()
t.Logf("%+v", status)
}
```
https://mattermost.atlassian.net/browse/MM-21143
=> MM-21143: implement SimpleController.reload

example/sampleuser/user.go, loadtest/user/user.go, loadtest/user/userentity/actions.go
Implement User.GetTeamsForUser
https://mattermost.atlassian.net/browse/MM-21233
=> MM-21233: Implement User.GetTeamsForUser

example/samplestore/store.go, example/sampleuser/user.go, loadtest/store/memstore/store.go, loadtest/store/store.go, loadtest/user/user.go, loadtest/user/userentity/actions.go
Implement User.GetRolesByNames
Verified by
```go
}))
})
})
err = …
```
=> MM-21235: Implement User.GetRolesByNames

example/sampleuser/user.go, loadtest/user/user.go, loadtest/user/userentity/actions.go
Implement User.GetAllTeams
Tested with:
```go
}))
})
})
err = c.user.AddChannelMember(channelId, …
```
=> MM-21236: Implement User.GetAllTeams

example/sampleuser/user.go, loadtest/user/user.go, loadtest/user/userentity/actions.go
Implement User.GetPostsAroundLastUnread
Tested with:
```go
}))
})
})
err = …
```
=> MM-21271: Implement User.GetPostsAroundLastUnread

example/sampleuser/user.go, loadtest/user/user.go, loadtest/user/userentity/actions.go
Implement User.AutocompleteChannelsForTeam
Tested with:
```go
}))
})
})
err = …
```
=> MM-21272: Implement User.AutocompleteChannelsForTeam

example/sampleuser/user.go, loadtest/user/user.go, loadtest/user/userentity/actions.go
This PR implements the `GetWebappPlugins` method. As other of its kind, we're not storing the outcome of the endpoint and we're using it to test the load in the server's endpoint
https://mattermost.atlassian.net/browse/MM-21274
=> Implements GetWebappPlugins in the user entity

.circleci/config.yml, Makefile
Now that we have moved to normal module fetch workflow, some additional
commands are needed to verify everything is working okay.
- We add a "go mod verify" command which matches the checksums in the DB
with the values in go.sum
- We also use the -mod=readonly flag during testing and building to ensure
that no additional modifications to go.mod happen during those commands.
This is similar to the "npm ci" command.
=> Add more module checks to CI

example/samplestore/store.go, example/sampleuser/user.go, loadtest/store/memstore/store.go, loadtest/store/memstore/store_test.go, loadtest/store/store.go, loadtest/user/user.go, loadtest/user/userentity/actions.go
Implement User.GetChannelMembersForUser
Tested with:
```go
}))
})
})
err = …
```
=> MM-21232: Implement User.GetChannelMembersForUser

example/sampleuser/user.go, loadtest/control/simplecontroller/actions.go, loadtest/control/simplecontroller/controller.go, loadtest/user/user.go, loadtest/user/userentity/user.go, loadtest/user/userentity/websocket.go
- The listener listens on the Event and Response channels.
And keeps reconnecting unless the Disconnect method was called explicitly.
- We also expose a SendWebsocketMessage method if in future we want to send
a message to the server.
Tested properly by checking for race conditions:
`$go test -race -v -run=UserConnect -count=1 .`
```go
func TestUserConnect(t *testing.T) {
user := New(memstore.New(), 0, Config{
})
email := fmt.Sprintf("testuser%d@example.com", user.Id())
username := fmt.Sprintf("testuser%d", user.Id())
password := "testPass123$"
err := user.SignUp(email, username, password)
err = user.Login()
err = user.Connect()
t.Log("user connected") …
```
=> MM-21283: Implement websocket listener

loadtest/store/memstore/store.go, loadtest/store/memstore/store_test.go, loadtest/store/memstore/utils.go
PR fixes an issue with user's password being set to empty which caused login errors.
https://mattermost.atlassian.net/browse/MM-21375
=> [MM-21375] Fix blanking user's password in MemStore.SetUser

example/samplestore/store.go, example/sampleuser/user.go, loadtest/control/simplecontroller/actions.go, loadtest/control/simplecontroller/controller.go, loadtest/store/memstore/store.go, loadtest/store/store.go, loadtest/user/user.go, loadtest/user/userentity/actions.go
- Invoke the commented methods which are now added
- Reorder it to happen after login
- Add Disconnect/Connect methods to it to better simulate a browser
https://mattermost.atlassian.net/browse/MM-21416
=> MM-21416: complete SimpleController.reload implementation

loadtest/control/controller.go, loadtest/control/simplecontroller/actions.go, loadtest/control/simplecontroller/controller.go, loadtest/control/status.go, loadtest/store/memstore/store.go, loadtest/store/store.go, loadtest/user/user.go, loadtest/user/userentity/user.go
https://mattermost.atlassian.net/browse/MM-21389
=> MM-21389: add godocs to most of the codebase

loadtest/control/simplecontroller/actions.go, loadtest/control/simplecontroller/controller.go
PR implements `SimpleController` actions to search for:
- Channels
- Users
- Posts
https://mattermost.atlassian.net/browse/MM-21556
=> [MM-21556] Implement actions to search

example/samplestore/store.go, example/sampleuser/user.go, loadtest/control/simplecontroller/actions.go, loadtest/control/simplecontroller/controller.go, loadtest/store/memstore/store.go, loadtest/store/memstore/store_test.go, loadtest/store/store.go, loadtest/user/user.go, loadtest/user/userentity/actions.go
PR implements actions to add and remove reactions.
It also implemented some missing/needed API and store methods.
https://mattermost.atlassian.net/browse/MM-21557
=> [MM-21557] Implement actions to add/remove reaction to/from a post

loadtest/control/simplecontroller/actions.go
finished viewChannel
Fixes https://mattermost.atlassian.net/browse/MM-21502
=> MM-21502  - Loadtest: complete SimpleController.viewChannel() implementation

loadtest/control/simplecontroller/actions.go
finished createPost
Fixes https://mattermost.atlassian.net/browse/MM-21504
=> MM-21504 - Loadtest: complete SimpleController.createPost()

example/samplestore/store.go, loadtest/control/simplecontroller/actions.go, loadtest/control/simplecontroller/controller.go, loadtest/store/memstore/store.go, loadtest/store/memstore/store_test.go, loadtest/store/store.go
added leave/join
Fixes https://mattermost.atlassian.net/browse/MM-21503
=> MM-21503  - Loadtest: implement action to join/leave a channel for SimpleController

api/server.go, api/server_test.go, config/config.go, loadtest/loadtest.go, loadtest/status.go
- Add custom Marshal/UnMarshal methods for Status.
- Use a proper response struct for all responses.
- Always add status when possible.
- Return a more apt StatusCreated when load agent gets created.
https://mattermost.atlassian.net/browse/MM-21677
=> MM-21677: Revamp HTTP API responses

api/server.go
Just noticed circleci has stopped working a while ago. This PR fixes the failures after merging the latest PRs.
=> Fix failures on master

loadtest/control/simplecontroller/controller.go, loadtest/user/userentity/user.go
PR fixes a panic (send on closed status channel) and also removes a couple of goroutines leaks.
https://mattermost.atlassian.net/browse/MM-21866
=> [MM-21866] Fix panic and goroutine leaks when stopping SimpleController

example/samplestore/store.go, loadtest/control/simplecontroller/actions.go, loadtest/control/simplecontroller/controller.go, loadtest/store/memstore/random.go, loadtest/store/memstore/random_test.go, loadtest/store/store.go
https://mattermost.atlassian.net/browse/MM-21668
=> MM-21668 implemented controller channel creation

api/server.go, coordinator/agent/agent.go, loadtest/loadtest.go
https://mattermost.atlassian.net/browse/MM-21914
=> MM-21914 - make Status optional

example/samplestore/store.go, loadtest/store/memstore/store.go, loadtest/store/store.go
https://mattermost.atlassian.net/browse/MM-21912
=> MM-21912  - implemented store.Clear()

.gitignore, cmd/loadtest/main.go, cmd/loadtest/terraform.go, config/config.default.json, loadtest/config.go, terraform/cluster.tf, terraform/create.go
- Use a basic terraform config file
- Add the terraform variables to our config file
- Take the variables and apply the configuration
https://mattermost.atlassian.net/browse/MM-22104
=> MM-22104: First cut of using terraform

loadtest/control/simplecontroller/actions.go
Currently, we keep on appending "new" which throws error
after a while because usernames have a limit of 22 characters maximum.
=> use a fixed username for updateProfile

cmd/loadtest/main.go, cmd/loadtest/terraform.go, terraform/destroy.go
We change the parent command to env and add 2 sub-commands
to create and destroy.
https://mattermost.atlassian.net/browse/MM-22217
=> MM-22217: ability to destroy a terraform environment

coordinator/cluster/cluster.go, coordinator/cluster/util.go, coordinator/cluster/utils_test.go
With this PR it is ensured to be a equal distribution among agents while increasing or decreasing their users.
https://mattermost.atlassian.net/browse/MM-22441
=> [MM-22441] coordinator/cluster: implement evenly distribution for inc/dec users

loadtest/store/memstore/random.go, loadtest/store/memstore/store.go
Added RW lock to Mutable Store
https://mattermost.atlassian.net/browse/MM-22435
=> MM-22437 loadtest: Data race in SimpleController websocket event handler

README.md, config/config.default.json, go.mod, loadtest/config.go, terraform/cluster.tf, terraform/create.go, terraform/destroy.go, terraform/outputs.tf, terraform/ssh.go, terraform/utils.go, terraform/variables.tf
Deploy mattermost from a given release URL using terraform.
https://mattermost.atlassian.net/browse/MM-22219
=> MM-22219: provision sotware with terraform

example/samplecontroller/controller.go, example/samplestore/store.go, loadtest/control/actions.go, loadtest/control/error.go, loadtest/control/simplecontroller/actions.go, loadtest/control/simplecontroller/controller.go, loadtest/control/simplecontroller/status.go, loadtest/control/simplecontroller/websocket.go, loadtest/control/simulcontroller/controller.go, loadtest/control/simulcontroller/status.go, loadtest/control/status.go, loadtest/control/utils.go, loadtest/control/utils_test.go, loadtest/loadtest.go, loadtest/store/memstore/random.go, loadtest/store/memstore/random_test.go, loadtest/store/memstore/store.go, loadtest/store/memstore/store_test.go, loadtest/store/store.go, loadtest/user/userentity/actions.go, loadtest/user/userentity/websocket.go
PR attempts to fix client side errors that were happening in user actions as a result of either missing or invalid data.
In the end it became a bit more involved than estimated due to some bugfix/additions that were required to make everything work properly.
PR also adds:
- a WebSocket event handler in the `userentity` package used to keep the `UserStore` in sync.
- a couple of random util functions to help picking a channel/team that the user is a member of.
- a fix for the action error origin that was broken by my previous refactor.
https://mattermost.atlassian.net/browse/MM-22438
=> [MM-22438] Fix client side errors in failing actions

api/server.go, cmd/loadtest/loadtest.go, config/config.default.json, coordinator/cluster/utils_test.go, docs/configuration.md, loadtest/config.go, loadtest/loadtest.go, loadtest/loadtest_test.go
- Add more validation checks
- Run the validation while initializing a *loadtest.Tester.
https://mattermost.atlassian.net/browse/MM-22442
=> MM-22442: Complete (*Config).IsValid

loadtest/control/actions.go, loadtest/control/utils.go, loadtest/control/utils_test.go
Add a logic for searching each letter in a search term for users/channels.
https://mattermost.atlassian.net/browse/MM-22891
=> [MM-22891] loadtest/user/actions: make an API call for each letter for search

loadtest/control/actions.go
Add documentation to the public user actions.
https://mattermost.atlassian.net/browse/MM-22711
=> [MM-22711] loadtest/actions: add docs to shared user actions

api/server.go, cmd/loadtest/loadtest.go, cmd/loadtest/terraform.go, coordinator/agent/agent.go, coordinator/agent/config.go, coordinator/cluster/cluster.go, coordinator/cluster/config.go, coordinator/config.go, coordinator/coordinator.go, coordinator/performance/config.go, coordinator/performance/monitor.go, loadtest/config.go, loadtest/loadtest.go
This PR introduces simplification on config validation methods.
https://mattermost.atlassian.net/browse/MM-23130
=> [MM-23130] Simplify configuration checks

loadtest/control/utils.go, loadtest/control/utils_test.go
Improve user typing emulation by adding random mistyping behavior.
https://mattermost.atlassian.net/browse/MM-23193
=> [MM-23193] loadtest/actions: improve user type emulation

api/server.go, cmd/loadtest/loadtest.go, loadtest/config.go, loadtest/control/noopcontroller/controller.go, loadtest/control/noopcontroller/status.go, loadtest/control/noopcontroller/websocket.go
https://mattermost.atlassian.net/browse/MM-22100
=> MM-22100  loadtest: implement a NOOP controller

config/simplecontroller.default.json, example/samplestore/store.go, loadtest/control/actions.go, loadtest/control/simplecontroller/controller.go, loadtest/store/memstore/random.go, loadtest/store/memstore/random_test.go, loadtest/store/store.go
Now that I have a rough idea of how likely it is for a user to reply to a post I have implemented an action for it.
https://mattermost.atlassian.net/browse/MM-23232
=> [MM-23232] Implement action to reply to a post

deployment/terraform/create.go
The bug was that io.MultiReader reads from the inputs serially
rather than concurrently. This would cause the stderr pipe to be
blocked up because nobody would read from it. And thereby
the entire command would get stuck.
We need to read from the inputs in separate goroutines.
https://mattermost.atlassian.net/browse/MM-23398
=> MM-23398: fix deployer getting stuck

deployment/terraform/cluster.tf, deployment/terraform/create.go, deployment/terraform/metrics.go, deployment/terraform/outputs.tf, deployment/terraform/strings.go
provision Prometheus server with Terraform
https://mattermost.atlassian.net/browse/MM-23375
=> MM-23375: provision Prometheus server with Terraform

deployment/terraform/cluster.tf, deployment/terraform/metrics.go
provision a Grafana server with Terraform and setup a datasource pointing to Prometheus. This does not add any dashboards for now. We can do it at a later stage.
https://mattermost.atlassian.net/browse/MM-23376
=> MM-23376: provision a Grafana server with terraform

example/sampleuser/user.go, loadtest/control/actions.go, loadtest/control/simplecontroller/controller.go, loadtest/user/user.go, loadtest/user/userentity/actions.go
This PR adds `PatchPost` action to the user actions.
https://mattermost.atlassian.net/browse/MM-23233
=> [MM-23233] Add PatchPost and related controller action

deployment/terraform/cluster.tf, deployment/terraform/metrics.go
This happens because cloud init wouldn't have been complete before the machine would be
termed ready. We fix this by checking for the presence of the file `/var/lib/cloud/instance/boot-finished` and then going ahead with the rest of the operations.
https://mattermost.atlassian.net/browse/MM-23422
=> MM-23422: Fix apt-get update not working

deployment/terraform/create.go
Without this, it will be very hard to run loadtests.
=> Enable external users to signup

config/deployer.default.json, deployment/config.go, deployment/terraform/cluster.tf, deployment/terraform/create.go, deployment/terraform/outputs.tf, deployment/terraform/variables.tf
Support clustered DB setups
https://mattermost.atlassian.net/browse/MM-23377
=> MM-23377: Support clustered DB setups

.circleci/config.yml, .golangci.yml
=> Bump to 1.14.1

loadtest/control/noopcontroller/controller.go, loadtest/control/simplecontroller/controller.go
PR moves user cleanup to the action loop goroutine also for `SimpleController` and `NoopController`.
This helps in fixing a [data race](https://gist.github.com/streamer45/99cef0f887895b729d0700ba818c67f7) by making sure `userentity` methods are called from the same goroutine.
At the same time we guarantee user actions stopped running before beginning to shutdown the controller.
https://mattermost.atlassian.net/browse/MM-23495
=> [MM-23495] Move user cleanup to action loop goroutine to avoid possible races

loadtest/control/simulcontroller/actions.go
PR fixes a panic caused by not handling the correct error.
https://mattermost.atlassian.net/browse/MM-23507
=> [MM-23507] Fix panic on some error cases

deployment/terraform/create.go
Display cluster information after deployment
https://mattermost.atlassian.net/browse/MM-23509
=> MM-23509: display cluster information after deployment

cmd/coordinator/main.go, cmd/deployer/main.go, cmd/loadtest/init.go, cmd/loadtest/loadtest.go, cmd/loadtest/main.go, cmd/loadtest/server.go, cmd/metricswatcher/main.go
https://mattermost.atlassian.net/browse/MM-23385
=> MM-23385 - SilenceUsage in cobra

deployment/config.go
https://mattermost.atlassian.net/browse/MM-23488
=> MM-23488 - added license file existence check

docs/simplecontroller_config.md
This PR adds documentation for the `SimpleController` config file.
https://mattermost.atlassian.net/browse/MM-23529
=> [MM-23529] Add simple controller config documentation

config/simplecontroller.default.json, docs/simplecontroller_config.md, loadtest/control/simplecontroller/actions.go, loadtest/control/simplecontroller/config.go, loadtest/control/simplecontroller/controller.go
Rename the field in the `simplecontroller` according to this [discussion](https://github.com/mattermost/mattermost-load-test-ng/pull/183#discussion_r399438931).
https://mattermost.atlassian.net/browse/MM-23685
=> [MM-23685] rename RunFrequency to RunPeriod

deployment/terraform/ssh/ssh.go
=> Fix incorrect param passed to Upload

Makefile
This PR adds a cleaner implementation for packaging the binaries.
=> Makefile: tweak packaging

Makefile
PR removes the unneeded README.md from the release package file and adds the license.
=> Remove README from package and add license file

.gitignore, cmd/ltcoordinator/main.go, config/config.default.json, config/coordinator.default.json, coordinator/cluster/config.go, coordinator/config.go, coordinator/coordinator.go
PR improves logging and configuration for `coordinator`:
- Made configurable the number of users to increment/decrement and the rest time in the feedback loop.
- Added proper config validation.
- Made the coordinator log into its own file.
https://mattermost.atlassian.net/browse/MM-23717
=> [MM-23717] Improve logging and configuration for coordinator

docs/deployer_config.md
his PR adds documentation for the `deployer` config file.
https://mattermost.atlassian.net/browse/MM-23530
=> [MM-23530] Add deployer config file documentation

.gitignore, config/deployer.default.json
PR updates `config/deployer.default.json` with new release.
Also, makes the deployer log into its own file.
=> Update deployer config

api/server.go, loadtest/control/simplecontroller/actions.go, loadtest/control/simplecontroller/controller.go, loadtest/control/simulcontroller/controller.go
- Reset the MemStore on various occasions.
https://mattermost.atlassian.net/browse/MM-23873
=> MM-23873: Add profile handlers

docs/terraform_loadtest.md
PR adds version requirement for Terraform in documentation.
https://mattermost.atlassian.net/browse/MM-23895
=> [MM-23895] Specify required Terraform version

config/deployer.default.json
=> Releasing v0.3.0-alpha

api/server.go, deployment/terraform/agent.go, deployment/terraform/create.go, loadtest/control/simulcontroller/actions.go
We are still not shifting the CI to 1.24.0
because there are bugs in that release.
=> Make codebase golangci 1.24.0 compliant

cmd/ltctl/main.go, deployment/terraform/create.go, deployment/terraform/info.go
- And also beautify the output.
https://mattermost.atlassian.net/browse/MM-23921
=> MM-23921: Add deployment info subcommand

deployment/terraform/ssh/ssh.go
PR fixes a couple of reported failures when running commands due to racy behaviour in `ssh.RunCommand`.
https://mattermost.atlassian.net/browse/MM-24073
=> [MM-24073] Fix racy behaviour in ssh.RunCommand

loadtest/user/userentity/websocket.go
Same issue as https://github.com/mattermost/mattermost-load-test-ng/pull/228, forgot this additional check.
=> Fix bad error check

loadtest/user/userentity/websocket.go
https://mattermost.atlassian.net/browse/MM-24324
=> MM-24324: do not close client if it was failed to be created

config/deployer.default.json
Switching to postgres makes a huge difference. Let's do that since majority of our customers use postgres anyways.
https://mattermost.atlassian.net/browse/MM-24447
=> MM-24447: Using postgres by default

cmd/ltagent/server.go, config/config.default.json, config/coordinator.default.json, config/deployer.default.json, deployment/config.go, loadtest/config.go
This PR changes the default log level for console.
=> update default log level for console with ERROR

config/deployer.default.json, deployment/terraform/create.go
=> Releasing v0.5.0-alpha

api/server.go, cmd/ltagent/init.go, cmd/ltagent/loadtest.go, loadtest/control/simulcontroller/controller_test.go, loadtest/loadtest_test.go, loadtest/store/memstore/config.go, loadtest/store/memstore/cqueue.go, loadtest/store/memstore/cqueue_test.go, loadtest/store/memstore/random_test.go, loadtest/store/memstore/store.go, loadtest/store/memstore/store_test.go, loadtest/user/userentity/helper_test.go
In the end stored data turned out to be not the main problem but still I thought a way to limit it (especially posts) would make sense and help with having long running load-testing sessions.
https://mattermost.atlassian.net/browse/MM-24396
=> [MM-24396] Limit amount of stored data in UserStore

go.mod, go.sum
https://mattermost.atlassian.net/browse/MM-24397
=> MM-24397: Point to custom branch with fix

deployment/terraform/create.go, loadtest/user/userentity/user.go
Increase them rather than decreasing them. It was a misunderstanding
of how timeouts work.
https://mattermost.atlassian.net/browse/MM-24930
=> MM-24930: Fix idle timeout settings

example/sampleuser/user.go, loadtest/control/actions.go, loadtest/control/simulcontroller/actions.go, loadtest/control/simulcontroller/utils.go, loadtest/control/utils.go, loadtest/control/utils_test.go, loadtest/user/user.go, loadtest/user/userentity/actions.go
This PR adds userentity action for `AutocompleteUsersInChannel` and uses it to include mentions to users when creating posts.
https://mattermost.atlassian.net/browse/MM-24643
=> [MM-24643] control/actions: add auto complete user name action

cmd/ltctl/collect.go, cmd/ltctl/main.go, deployment/terraform/collect.go, deployment/terraform/ssh/ssh.go
PR implements a new `ltctl collect` command to help collecting files (logs and configurations) needed to aid debugging.
https://mattermost.atlassian.net/browse/MM-25008
=> [MM-25008] Implement collect command

config/deployer.default.json, deployment/terraform/create.go
Releasing mattermost-load-test-ng-v0.6.0-alpha
=> Releasing v0.6.0-alpha

deployment/terraform/create.go
It is causing more harm than good.
=> Make read-only to false

loadtest/user/userentity/actions.go
https://mattermost.atlassian.net/browse/MM-25141
=> MM-25141: fix nil pointer panic in AutocompleteUsersInChannel

api/server.go, cmd/ltagent/init.go, cmd/ltagent/loadtest.go, go.sum, loadtest/control/simulcontroller/controller_test.go, loadtest/loadtest_test.go, loadtest/user/userentity/helper_test.go, loadtest/user/userentity/metrics.go, loadtest/user/userentity/user.go, loadtest/user/userentity/user_test.go, loadtest/user/userentity/websocket.go, performance/metrics.go
PR exposes some basic metrics for the load-test agent.  
This could be seen as ultimately closing the [feedback loop](https://github.com/mattermost/mattermost-load-test-ng/blob/master/docs/coordinator.md#the-feedback-loop). Whether or not we are going to feed any of this data to the coordinator has yet to be seen (still preparing [MM-22444](https://mattermost.atlassian.net/browse/MM-22444)) but in any case I think it's good to have them since they might offer new insights into potential performance problems (or even client-side bugs).
A PR to follow for the integration in the system and possibly some new Grafana panels.
https://mattermost.atlassian.net/browse/MM-25610
=> [MM-25610] Expose some basic metrics for ltagent

docs/local_loadtest.md
- Update controller config switch in docs. It was changed in 9ab65fbfd4a28c16a5b0f8bff2a4b2d2a7c2c8c6
- N/A
=> update controller config switch in docs

docs/controllers.md, docs/gencontroller_config.md, docs/generating_data.md, docs/loadtest_config.md, loadtest/control/gencontroller/config.go
PR adds documentation for `GenController`.
https://mattermost.atlassian.net/browse/MM-24527
=> [MM-24527] Add GenController documentation

loadtest/control/simplecontroller/actions.go
https://mattermost.atlassian.net/browse/MM-26079
=> MM-26079: fix panic during scroll channel

docs/compare.md
This PR adds some best practices that are useful when comparing results from different load-tests.
=> Add best practices for comparing load-tests

loadtest/user/websocket/client.go
This PR changes the log level for an expected scenario for websocket client.
https://mattermost.atlassian.net/browse/MM-26168
=> [MM-26168] websocket/client: change log level for close error

config/deployer.sample.json, deployment/terraform/create.go
=> Releasing v0.7.0-alpha

loadtest/report/compare.go, loadtest/report/compare_test.go
We were using the wrong index to append further reports.
https://mattermost.atlassian.net/browse/MM-26558
=> MM-26558: Fix index for multi-report comparison

loadtest/report/output.go
Makes it look a bit more nice and clean.
=> Use weighted lines for graphs instead of points

cmd/ltctl/main.go, cmd/ltctl/report.go
https://mattermost.atlassian.net/browse/MM-26496
=> MM-26496: pass Prometheus server URL from a flag

docs/deployer_config.md, example/samplestore/store.go, loadtest/config.go, loadtest/control/simplecontroller/websocket.go, loadtest/store/memstore/store.go, loadtest/store/memstore/store_test.go, loadtest/store/store.go, loadtest/user/user.go, loadtest/user/userentity/actions.go, loadtest/user/userentity/user.go
PR reviews some documentation mainly for the User and Store interfaces.
https://mattermost.atlassian.net/browse/MM-23498
=> [MM-23498] Review User and Store documentation

docs/terraform_loadtest.md
I forgot to add this when I implemented the new command.
=> Add status command to terraform docs

api/client/agent/agent.go, coordinator/cluster/cluster.go
Using the new client driver broke this behaviour. PR fixes it.
https://mattermost.atlassian.net/browse/MM-26786
=> [MM-26786] Fix agents not getting restarted in case of crash

loadtest/user/websocket/client_test.go
PR fixes a race condition happening in `websocket/client_test.go` by waiting for `dummyWebsocketHandler` to finish before closing the server and exiting the test.
https://mattermost.atlassian.net/browse/MM-26787
=> [MM-26787] Fix flaky websocket/client_test.go

loadtest/report/compare.go
https://mattermost.atlassian.net/browse/MM-27115
=> MM-27115: Fix incorrect base for delta percentage

config/coordinator.sample.json, coordinator/config.go
PR reviews and improves coordinator's sample config.
I've left a few comments explaining the proposed changes.
https://mattermost.atlassian.net/browse/MM-26859
=> [MM-26859] Review coordinator config

loadtest/control/gencontroller/controller.go
PR fixes a couple of cases where `gencontroller` (and the init process as a consequence) could get stuck without never exiting.
https://mattermost.atlassian.net/browse/MM-27469
=> [MM-27469] Fix cases where gencontroller could get stuck

examples/loadtest/sampleuser/user.go, loadtest/control/simulcontroller/actions.go, loadtest/control/simulcontroller/controller.go, loadtest/control/utils.go, loadtest/control/utils_test.go, loadtest/user/user.go, loadtest/user/userentity/actions.go
PR adds some missing search related actions to `SimulController`.
https://mattermost.atlassian.net/browse/MM-27330
=> [MM-27330] Add some missing search related actions

deployment/terraform/create.go, deployment/terraform/utils.go
PR adds a MM license validation check before creating a new deployment.
https://mattermost.atlassian.net/browse/MM-27486
=> [MM-27486] Add license validation check before deploying

config/deployer.sample.json, deployment/config.go, deployment/terraform/create.go
=> Releasing v1.1.0

.goreleaser.yml, Makefile, README.md, docs/developing.md
PR implements the required steps to (mostly) automate the release process.
It adds a `release` target to the `Makefile` that will update the version strings in the code, commit, add a new git tag and finally call [goreleaser](https://goreleaser.com/) to handle build, packaging and publishing to Github.
All this process should now be automated by a single command, e.g.:
```NEXT_VER=v1.1.1 make release```.
https://mattermost.atlassian.net/browse/MM-28656
=> [MM-28656] Automate release process

deployment/terraform/coordinator.go
PR fixes starting a load-test on agents only deployments.
https://mattermost.atlassian.net/browse/MM-29006
=> [MM-29006] Allow starting load-test on agents only deployments

config/deployer.sample.json
I did notice Github's UI complaining in last PR but couldn't spot the error.
=> Fix JSON in deployer.sample.json

docs/compare.md, loadtest/report/compare.go, loadtest/report/output.go, loadtest/report/output_test.go
PR fixes some rather stupid bugs introduced in https://github.com/mattermost/mattermost-load-test-ng/pull/390.
Funny thing, the attached sample report was full of issues but nobody noticed (myself included :facepalm: ).
https://mattermost.atlassian.net/browse/MM-30510
=> [MM-30510] Fix sorted store and api times in output Markdown

README.md, docs/faq.md
For the joy of @agnivade :grin:  
PR adds FAQ and Troubleshoot sections. From now on it will be easier to keep track of common issues/questions.
Please feel free to remind me of more things to add because I am surely missing a lot.
Also let me know if you'd prefer a link to these in the README.
https://mattermost.atlassian.net/browse/MM-30788
=> [MM-30788] Add FAQ section

comparison/config.go, docs/comparison.md, docs/comparison_config.md, docs/terraform_loadtest.md
PR adds some documentation related to the new `comparison` command.
https://mattermost.atlassian.net/browse/MM-30990
=> [MM-30990] Add documentation for comparison command

deployment/terraform/create.go
PR fixes an issue happening sporadically when attempting to re-deploy. The server would fail to restart and eventually cause the server status check to timeout.
This is because on subsequent deploy runs we are uploading the config file without making sure the server is stopped. This was causing a sort of race condition where at the same time of the upload the server was writing to the config file making the result garbled. 
https://mattermost.atlassian.net/browse/MM-31544
=> [MM-31544] Fix server sporadically failing to restart

config/deployer.sample.json, deployment/config.go, deployment/terraform/create.go
Releasing v1.2.0  
This was due for a long time.
=> Releasing 1.2.0

docs/faq.md, docs/local_loadtest.md
PR updates docs with some missing information which were causing some confusion on new users.
https://mattermost.atlassian.net/browse/MM-31777
=> [MM-31777] Update docs

docs/faq.md, loadtest/loadtest.go, loadtest/utils.go
PR improves the error in case the limit of file descriptors is reached by proposing a working value.
https://mattermost.atlassian.net/browse/MM-31921
=> [MM-31921] Improve error and documentation when file descriptor limit is reached

cmd/ltctl/collect.go
[MM-32592](https://mattermost.atlassian.net/browse/MM-32592)
=> Fix collect ltagent.log files

comparison/comparison.go, comparison/output.go
PR improves the comparison results generation logic by:
- Processing results concurrently.
- Making the overall process more resilient by logging errors instead of exiting abruptly.
https://mattermost.atlassian.net/browse/MM-32237
=> [MM-32237] Improve comparison results generation logic

config/deployer.sample.json, deployment/terraform/strings.go
PR introduces some changes to proxy related config settings that showed good performance improvement in terms of supported user counts.
https://mattermost.atlassian.net/browse/MM-26764
=> [MM-26764] Improve proxy performance

deployment/terraform/engine.go
=> deployment/terraform/engine: fix prompt

README.md, docs/coverage.md
I've created a small document to help developers to add load-test coverage for their new features.
This will be accompanied by a video walk-through where I actually implement coverage for a sample feature so I kept the doc rather simple and mainly listed where are the places to look at without going into too much details.
Please let me know if I've missed anything important and/or if you think something needs further clarification.
Live preview can be found [here](https://github.com/mattermost/mattermost-load-test-ng/blob/MM-31691/docs/coverage.md).
https://mattermost.atlassian.net/browse/MM-31691
=> [MM-31691] Add document on how to add new load-test functionality

.circleci/config.yml, .golangci.yml, cmd/ltctl/reset.go, comparison/loadtest.go, loadtest/control/clustercontroller/controller.go
PR upgrades `golangci-lint` to the latest version and fixes the reported errors.
=> Upgrade linter

config/deployer.sample.json, deployment/config.go
=> Releasing v1.3.0

config/deployer.sample.json, deployment/config.go, docs/setups.md
After the recent performance tunings I forgot to update this.
=> Update agent instance type

deployment/terraform/create.go, loadtest/control/simulcontroller/actions.go, loadtest/control/utils.go, loadtest/control/utils_test.go
Posts will randomly contain links now.
Also made it part of the deployment config.
=> Added LinkPreview feature

loadtest/control/simulcontroller/actions.go, loadtest/control/simulcontroller/controller.go, loadtest/user/user.go, loadtest/user/userentity/actions.go
Not the most frequent of actions but, as we are reminded as of late, anything dealing with posts can be important from a performance perspective.
=> Implement `deletePost` action

.golangci.yml, api/client_test.go
- Make lint exclusions more specific to issues in our code instead of skipping entire folders. This should prevent more lint errors from creeping in until we fix the existing issues. 
- NA
=> make lint exclusions more specific

loadtest/control/simulcontroller/actions.go
10% of all posts is too much it seems.
Bringing it down to 1%.
=> Tune permalink creation frequency

loadtest/control/simulcontroller/actions.go
Same thing as https://github.com/mattermost/mattermost-load-test-ng/pull/487 really.
https://mattermost.atlassian.net/browse/MM-43618
=> Fix possible panic in `SimulController.unfollowThread`

config/deployer.sample.json
=> Using a newer DB class

cmd/ltctl/reset.go, docs/comparison.md, docs/controllers.md, docs/deployer_config.md, docs/terraform_loadtest.md
These are minor docs fixes I had in a branch I created when I first had to deal with this repo. Nothing important nor urgent, just fixes here and there :)
--
=> Docs fixes

README.md, docs/load-test-how-to-use.md, docs/terraform_loadtest.md
Creates a doc which acts as a walkthrough of steps to use `mattermost-load-test-ng`.
NA
=> Add generic user workflow docs

cmd/ltctl/loadtest.go
This is something that could have saved me a couple of minutes when debugging https://community.mattermost.com/core/pl/szznbrc8jjdu7po5pnt7o9uyny. Nothing critical, but now a bit more helpful.
--
=> Improve error message when failing to query Prometheus

cmd/ltctl/comparison.go
Fixes https://github.com/mattermost/mattermost-server/issues/20884
=> check for gnuplot for comparison command

comparison/loadtest.go, deployment/terraform/create.go
There are multiple places where we assume that the default language in the database is `english` (e.g., the GIN indexes are hardcoded to `english`), but the `default_text_search_config` parameter in Aurora defaults to `simple`. It is not possible to change that in the config level in AWS, so these changes make sure that the parameter has the expected value by altering the DB itself in two places:
- When creating any new Terraform deployment
- When running a comparison, which needs to reset the param after dropping and recreating the DB.
This has been tested with:
- `go run ./cmd/ltctl deployment create`
- `go run ./cmd/ltctl comparison run`
https://mattermost.atlassian.net/browse/MM-47265
=> MM-47265: Set default_text_search_config to english

cmd/metricswatcher/prometheushealthcheck/healthprovider.go, deployment/terraform/metrics.go
Path to Filepath change #21480
=> path to filepath change #21480

config/deployer.sample.json, deployment/config.go
PR created with `NEXT_VER=v1.7.1 make prepare-release`
--
=> Bump version to v1.7.1

deployment/terraform/strings.go
See context in #532. I'll run a test with this and merge when it's verified to work.
--
=> Bump LimitNOFILE to 2^18

Makefile
A rule heavily inspired (i.e. copied) from mattermost-server rule.
--
=> Add a rule to update dependencies

.golangci.yml
Agniva demanded I remove the old packages from the list.
https://community.mattermost.com/core/pl/tk7m3z75r3yodr614dt38y68cw
=> Remove deprecated linters from golangci

docs/developing.md
Just a hint to use make assets
--
=> Add brief docs on make assets

docs/terraform_loadtest.md
Just attempting to clarify what happens if there is a clash on `ClusterName`. I cannot imagine a ton of customers will hit this, but just in case.
=> Update deployment docs to clarify `ClusterName`

config/deployer.sample.json, deployment/config.go
Prepare a new release to test Mattermost v7.9-RC1 with the latest changes in master.
--
=> Bump version to 1.8.0

loadtest/user/userentity/metrics.go, loadtest/user/userentity/user.go, performance/metrics.go
Cherry-pick #572 into release-1.8 to release a v1.8.1
=> Cherry-pick #572: MM-51097: Revert improvement to HTTPRequestTimes metric

config/deployer.sample.json, deployment/config.go
=> Bump version to v1.8.1

config/deployer.sample.json
Switch to graviton instances for RDS
https://mattermost.atlassian.net/browse/MM-51223
=> Switch to graviton instances for RDS

config/deployer.sample.json, deployment/config.go
Preparation for a new release with only #581 included.
--
=> Bump version to v1.9.1

loadtest/control/gencontroller/actions.go
We just pick 2 random words separated by _.
It's a decent improvement for now.
https://mattermost.atlassian.net/browse/MM-52988
=> MM-52988: Improve channel name generation logic

loadtest/store/memstore/random.go, loadtest/store/memstore/random_test.go
Things become to ergonomic with generics.
You don't even need to have some tests because of
the compile-time validation.
=> Improve pickRandomKeyFromMap to use generics

deployment/terraform/metrics.go, deployment/terraform/strings.go
Add Pyroscope monitoring for all the agents in the deployment. This has been tested with the latest several-days-long load-test and it worked as expected.
--
=> Monitor agents in Pyroscope

docs/faq.md
Felipe was reading this bit of the docs and we realized it was slightly confusing, so I just reworded it to have three separate sections:
- Definition of bounded test
- Definition of unbounded test
- Configuration needed to choose between one or the other
Let me know if it's better now, we can keep iterating on it if needed.
--
=> Add a FAQ to clarify how to configure a test to be bounded or unbounded

loadtest/control/gencontroller/actions.go, loadtest/control/gencontroller/controller.go, loadtest/control/gencontroller/state.go, loadtest/user/userentity/actions.go
- Corrected some log lines
- Calling GetUsers just once because it was overloading the servers and we didn't need that any more after all users have logged in.
- Paginating through GetUsers response
=> Some minor improvements

cmd/ltagent/init.go
Changes in https://github.com/mattermost/mattermost-load-test-ng/pull/608 broke the `init` command as we used to set `InitialActiveUsers` to zero and add users later on, which would result in the config validation check for `gencontroller` to fail. 
I am not entirely sure why we used to add the users after starting the load-test but I can't see a strong reason to keep doing that. Please let me know if I am missing something.
=> Fix init command

docs/faq.md
Fix in the name of the config.
--
=> Fix FAQ entry

loadtest/control/gencontroller/actions.go, loadtest/control/gencontroller/controller.go
I am adding a loop to take care of any required action so that we guarantee they pass before moving forward with the execution since any of those failing makes it almost pointless to continue for the affected user.
=> Implement required actions loop

loadtest/control/simulcontroller/actions.go, loadtest/control/simulcontroller/utils.go, loadtest/user/userentity/actions.go
This logic was missed out and since we already do autocomplete,
therefore we make it more realistic.
https://mattermost.atlassian.net/browse/MM-53729
=> MM-53729: Load profile images while doing user autocomplete

docs/developing.md, docs/release.md
This PR proposes a new release process, with a fixed timeline and owners, to ensure released versions are well tested and stable. It is simple by design, we can always iterate on it when needed.
Adding everyone in the team that may be part of it as stated in the doc as reviewers.
Everything in this document is up to discussion, there's nothing set in stone, so feel free to disagree with some or even all of it :)
https://mattermost.atlassian.net/browse/MM-53646
=> MM-53646: First version of the release process

cmd/ltctl/collect.go, cmd/ltctl/comparison.go, cmd/ltctl/main.go, comparison/comparison.go, comparison/comparison_test.go
Just some quality-of-life improvement that I've been wanting to do forever, and today I decided to throw some code at it. I just tested with the current comparison I'm running and it works.
https://mattermost.atlassian.net/browse/MM-46253
=> MM-46253: Comparison collect command

config/deployer.sample.json, deployment/config.go, deployment/config_test.go
Bump the version to v1.10.0-rc1 in the release-1.10 branch.
--
=> Bump version to v1.10.0-rc1

config/deployer.sample.json, deployment/config.go, deployment/config_test.go
=> Bump version to v1.11.0

.goreleaser.yml, Makefile
For the last couple of releases, I've been manually doing a set of steps instead of relying 100% on the Makefile commands. This PR adds those manual steps to the corresponding commands so that it's not only me who knows how to do it :)
Changes are explained in the commit messages.
--
=> Fix Makefile's release commands

config/deployer.sample.json, deployment/config.go, deployment/config_test.go
=> Bump to v1.12.0

go.mod, go.sum, loadtest/control/simulcontroller/actions.go, loadtest/user/user.go, loadtest/user/userentity/actions.go
This PR fixes the type issues that were caused by my load test PR being merged. We had changed the types a couple times between when the PR was created and when it was merged, so I didn't realize that we had breaking changes.
https://mattermost.atlassian.net/browse/MM-55728
=> [MM-55728] Fix types in load test for user reporting

config/deployer.sample.json, deployment/config.go, deployment/config_test.go
Preparing the pre-release of v1.13.0
--
=> Bump version to v1.13.0-rc1

loadtest/control/gencontroller/actions.go, loadtest/control/simulcontroller/actions.go
Cherrypick #685 to `release-1.13` in order to cut a new RC-2.
--
=> Cherrypick #685 to 1.13

config/deployer.sample.json, deployment/config.go, deployment/config_test.go
=> Bump version to v1.13.0-rc2

config/deployer.sample.json, deployment/config.go, deployment/config_test.go
Beginning the release process for `v1.13.0`
=> Bump version to v1.13.0

deployment/terraform/create.go
https://mattermost.atlassian.net/browse/MM-54860
=> MM-54860: Automatically vacuum tables after deployment

config/deployer.sample.json, deployment/config.go, deployment/config_test.go
Start process to release v1.14.0
--
=> Bump version to v1.14.0-rc1

config/deployer.sample.json, deployment/config.go, deployment/config_test.go
Bump version to v1.14.0. I promise this is the last PR I open today, @streamer45 :nerd_face: 
--
=> Bump version to v1.14.0

deployment/terraform/strings.go
- Removing the graphQL flag.
- Setting the websocket event scope flag to always true.
=> Updating some feature flags

config/deployer.sample.json, deployment/config.go, deployment/config_test.go
I need to do the "latest release" thing because this process is tedious.
This is the second-to-last PR of today, I swear.
=> Bump version to v1.15.0-rc2

config/deployer.sample.json, deployment/config.go, deployment/config_test.go
And the last one of today!
Thank you for your patience.
--
=> Bump version to v1.15.0-rc2 (#713)

config/deployer.sample.json, deployment/config.go, deployment/config_test.go
Bumping it in master as per the new process, will cherry-pick to the branch later on.
--
=> Bump version to v1.15.0

config/deployer.sample.json, deployment/config.go, deployment/config_test.go
=> Bump to v1.15.0

loadtest/control/simulcontroller/actions.go
https://mattermost.atlassian.net/browse/MM-57354
=> MM-57354: Fetch static assets

cmd/ltctl/main.go, deployment/terraform/create.go, deployment/terraform/strings.go, docs/terraform_loadtest.md
https://mattermost.atlassian.net/browse/MM-57355
=> MM-57355: Moving to a test service env

config/deployer.sample.json, deployment/config.go, deployment/config_test.go
Bump version to v1.16.0-rc1
--
=> Bump version to v1.16.0-rc1

loadtest/user/user.go, loadtest/user/userentity/user.go, loadtest/user/userentity/websocket.go, loadtest/user/websocket/client.go
I had changed the server code to use `status` but forgot to change it here, see: https://github.com/mattermost/mattermost/pull/26799
=> Use "status" as the posted ACK result instead of "result"

config/deployer.sample.json, deployment/config.go, deployment/config_test.go
=> Bump version to v1.16.0

config/deployer.sample.json, deployment/config.go, deployment/config_test.go
Soon([ish](https://mattermost.atlassian.net/browse/CLD-7570)), this won't be needed. But it is for now :(
--
=> Bump version to v1.17.0-rc1

config/deployer.sample.json, deployment/config.go, deployment/config_test.go
Bumping versions all day long.
--
=> Bump version to v1.17.0

deployment/elasticsearch/roundtripper_test.go
https://mattermost.atlassian.net/browse/MM-58444
=> MM-58444: Skipping flaky test

config/deployer.sample.json, deployment/config.go, deployment/config_test.go
Building our way to v1.18 :walking: 
--
=> Bump version to v1.18.0-rc1

config/deployer.sample.json, deployment/config.go, deployment/config_test.go
=> Bump version to v1.18.0

config/deployer.sample.json, deployment/config.go, deployment/config_test.go
And bumping it in master to keep it up to date. (Still waiting for https://mattermost.atlassian.net/browse/CLD-7570)
--
=> Bump version strings in master

config/coordinator.sample.json
Halve the value based on latest test results
Context: https://community.mattermost.com/core/pl/ni9jbytuttr35fa3tu7xmhf5uy
=> Update retransmission threshold

config/deployer.sample.json, deployment/config.go, deployment/config_test.go
Another month, another release.
--
=> Bump version to v1.19.0-rc1

config/deployer.sample.json, deployment/config.go, deployment/config_test.go
=> Bump v1.19.0 rc2

deployment/terraform/strings.go
Cherry-pick #768 into `release-1.19`
--
=> Cherry-pick #768

config/deployer.sample.json, deployment/config.go, deployment/config_test.go
Fixing the merging mess-up...
I merged #770 into `master` instead of `release-1.19`. This does merge the changes into the correct branch. I'll leave the other commit in `master` because we're updating it right after the release anyway. I cannot wait for https://mattermost.atlassian.net/browse/CLD-7570 to happen :sob: 
Sorry, guys!
=> Bump version to v1.19.0-rc2

config/deployer.sample.json, deployment/config.go, deployment/config_test.go
=> Bump version to v1.19.0

config/deployer.sample.json, deployment/config.go, deployment/config_test.go
Bumping versions in master as well.
(My kingdom for https://mattermost.atlassian.net/browse/CLD-7570)
--
=> Bump version to v1.19.0 in master

deployment/terraform/create.go, loadtest/control/actions.go, loadtest/control/simulcontroller/controller.go, loadtest/control/simulcontroller/drafts.go, loadtest/control/utils.go, loadtest/store/memstore/random.go, loadtest/store/memstore/store.go, loadtest/store/memstore/utils.go, loadtest/store/store.go, loadtest/user/user.go, loadtest/user/userentity/drafts.go
While here, we also make some improvements:
- Use model.NewPointer.
- Use clear builtin to clear slices and maps.
=> Add drafts support

config/deployer.sample.json, deployment/config.go, deployment/config_test.go
=> Bump version to v1.20.0

config/deployer.sample.json, deployment/config.go, deployment/config_test.go
Bump version to v1.20 in master.
--
=> Bump version to v1.20 in master

deployment/config.go, deployment/config_test.go, deployment/opensearch/opensearch.go, deployment/opensearch/roundtripper.go, deployment/opensearch/roundtripper_test.go, deployment/terraform/create.go, go.mod, go.sum
https://mattermost.atlassian.net/browse/MM-57876
=> MM-57876: Use opensearch only

config/deployer.sample.json, deployment/config.go, deployment/config_test.go
Bump version to v1.21.0-rc1
--
=> Bump version to v1.21.0-rc1

config/deployer.sample.json, deployment/config.go, deployment/config_test.go
=> Bump version to v1.21.0

config/deployer.sample.json, deployment/config.go, deployment/config_test.go
Bump version to v1.21.0 in master
--
=> Bump version to v1.21.0 in master

config/deployer.sample.json, deployment/config.go, deployment/config_test.go
Bump version to v1.22.0-rc1
--
=> Bump version to v1.22.0-rc1

config/deployer.sample.json, deployment/config.go, deployment/config_test.go
=> Bump version to v1.22.0

config/deployer.sample.json, deployment/config.go, deployment/config_test.go
https://mattermost.atlassian.net/browse/CLD-7570 is in progress now! Maybe next month we don't need this :)
--
=> Bump version to v1.23.0-rc1

config/deployer.sample.json, deployment/config.go, deployment/config_test.go
=> Bump version to v1.23.0

config/deployer.sample.json, deployment/config.go, deployment/config_test.go
=> Bump to v1.23.0 in master

config/deployer.sample.json, config/deployer.sample.toml, deployment/config.go, deployment/config_test.go, examples/config/ci/deployer.json
=> Bump version to v1.24.0-RC1

cmd/ltctl/main.go, deployment/terraform/utils.go
Add keycloak support for the ssh command.
https://mattermost.atlassian.net/browse/MM-61282
=> [MM-61282] added keycloak support for the ssh command

Makefile
We need to replace the string of the latest version in TOML files as well
No ticket, just this comment from @streamer45: https://github.com/mattermost/mattermost-load-test-ng/pull/866#pullrequestreview-2493646237 :)
=> Include TOML config files in strings replacement

config/deployer.sample.json, config/deployer.sample.toml, deployment/config.go, deployment/config_test.go, examples/config/ci/deployer.json
Another version, another bump
--
=> Bump version to v1.24.0

config/deployer.sample.json, config/deployer.sample.toml, deployment/config.go, deployment/config_test.go, examples/config/ci/deployer.json
And in master. Last PR like this at least for 2024 :)
--
=> Bump v1.24.0 in master

config/deployer.sample.json, config/deployer.sample.toml, deployment/config.go, deployment/config_test.go, examples/config/ci/deployer.json
Bump version to v1.25.0-rc1
--
=> Bump version to v1.25.0-rc1

config/deployer.sample.json, config/deployer.sample.toml, deployment/config.go, deployment/config_test.go, examples/config/ci/deployer.json
Just that :man_shrugging: Still waiting for https://mattermost.atlassian.net/browse/CLD-7570 :sob: 
--
=> Bump strings to v1.25.0 in master

Makefile, config/deployer.sample.json, config/deployer.sample.toml, deployment/config.go, deployment/config_test.go, examples/config/ci/deployer.json
Cherry-pick #895 to release-1.24
https://mattermost.atlassian.net/browse/MM-63351
=> Cherry-pick #895 to release-1.24

examples/config/ci/deployer.json
Cherry-pick #899 so we can make a new patch release.
--
=> Cherry pick #899

docs/readme.md
Fix Broken Link for Generating Data
Note: Link from pr preview doesn't work.
=> Fix Broken Link for Generating Data

deployment/terraform/keycloak.go
Add the needed flag to enable metrics in Keycloak. 
https://mattermost.atlassian.net/browse/MM-64219
=> MM-64219: Add flag to enable metrics in Keycloak

loadtest/control/actions.go
Cherry-pick #922 to `release-1.27` so that we can release a new v1.27.1.
--
=> Cherry-pick #922 (Revert change from #908)

api/agent.go
Cherry-pick #925 to `release-1.27`, so that we can release 1.27.2.
--
=> Cherry-pick #925 to release-1.27

loadtest/user/userentity/actions.go
=> Cherry-pick: Remove new logic for GetChannelMembersWithTeamData (#935)

deployment/terraform/ssh/ssh.go, go.mod, go.sum
Replaces the `cat` upload file approach with an sftp library.
=> feat: upload files via sftp

loadtest/store/memstore/store.go, loadtest/store/memstore/store_test.go
Cherry-pick #942 into `release-1.28`
https://mattermost.atlassian.net/browse/MM-64881
=> Cherry-pick #942 into release-1.28
